# -*- coding: utf-8 -*-
"""
Full Authentic Curriculum for Levels 5 & 6 (Lessons 141 to 160)
20 lessons = 230 unique questions (10*12 + 10*11), 80 quizzes, 80 practice exercises.
"""

CURRICULUM_L5_L6 = {
    141: {
        "title": "Indirect Questions in Technical Support",
        "questions": [
            ("Choose the polite indirect question asking for server logs:", ["Could you please let me know where the Nginx access logs are stored?", "Where are the Nginx access logs stored tell me?", "Could you please let me know where are stored the Nginx access logs?", "Tell me where the Nginx access logs are."], "Could you please let me know where the Nginx access logs are stored?", "Question indirecte : ordre SVO dans la subordonnée."),
            ("Select the indirect question verifying firewall configuration:", ["Do you happen to know if port 8443 is open on the edge router?", "Do you happen to know is port 8443 open on the edge router?", "Do you happen to know whether is port 8443 open on the edge router?", "Know you if port 8443 is open?"], "Do you happen to know if port 8443 is open on the edge router?", "if / whether + sujet + verbe."),
            ("Complete: 'I was wondering ___ we could schedule an architecture review this Thursday.'", ["whether", "is that", "what", "which"], "whether", "'whether' pour une interrogation indirecte polie."),
            ("Choose the sentence with correct word order after 'Can you tell me':", ["Can you tell me why the authentication pod crashed at 03:00 UTC?", "Can you tell me why did the authentication pod crash at 03:00 UTC?", "Can you tell me why crashed the authentication pod at 03:00 UTC?", "Can you tell me why was the authentication pod crash at 03:00 UTC?"], "Can you tell me why the authentication pod crashed at 03:00 UTC?", "Pas d'inversion auxiliaire dans la subordonnée."),
            ("Select the polite customer support phrasing: 'Would you mind confirming which operating system version is installed on the host?'", ["Would you mind confirming which operating system version is installed on the host?", "Would you mind confirming which operating system version is installed on the host did you?", "Would you mind confirming which is installed operating system version on the host?", "Would you mind to confirm which operating system version is installed on the host?"], "Would you mind confirming which operating system version is installed on the host?", "Would you mind + gérondif + subordonnée SVO."),
            ("Complete: 'I would appreciate it if you could clarify ___ the database migration was executed.'", ["when", "did when", "when was", "when did"], "when", "clarify when it was executed."),
            ("Choose the indirect question asking about user permissions:", ["Could you clarify whether the service account has administrative privileges in AWS?", "Could you clarify does the service account have administrative privileges in AWS?", "Could you clarify has the service account administrative privileges in AWS?", "Could you clarify whether has the service account administrative privileges in AWS?"], "Could you clarify whether the service account has administrative privileges in AWS?", "whether + subject + verb."),
            ("Complete: 'Do you know how frequently the backup job ___ in production?'", ["runs", "does run", "is run", "running"], "runs", "how frequently the job runs."),
            ("Select the professional customer support opening: 'I would be grateful if you could provide the trace ID associated with the 502 error.'", ["I would be grateful if you could provide the trace ID associated with the 502 error.", "Give me trace ID now for 502.", "Provide trace ID immediately please.", "I want trace ID from 502."], "I would be grateful if you could provide the trace ID associated with the 502 error.", "Formule polie d'assistance technique."),
            ("Complete: 'Could you confirm ___ the issue persists after clearing the browser cache?'", ["if", "did", "does", "is"], "if", "confirm if the issue persists."),
            ("Choose the indirect question asking about reproduction steps:", ["Could you describe how we can reproduce this defect in our staging environment?", "Could you describe how can we reproduce this defect in our staging environment?", "Could you describe how do we can reproduce this defect in our staging environment?", "Could you describe how reproduce we this defect in our staging environment?"], "Could you describe how we can reproduce this defect in our staging environment?", "how we can reproduce."),
            ("Select the sentence with accurate punctuation: 'I was wondering if you had time to review this pull request.'", ["I was wondering if you had time to review this pull request.", "I was wondering if you had time to review this pull request?", "I was wondering did you have time to review this pull request.", "I was wondering if had you time to review this pull request?"], "I was wondering if you had time to review this pull request.", "'I was wondering...' se termine par un point.")
        ],
        "quiz": [
            ("What happens to word order in an indirect question clause?", ["The clause reverts to standard declarative Subject + Verb order", "The clause keeps auxiliary inversion", "The verb moves to the very beginning", "All verbs become infinitives"], "The clause reverts to standard declarative Subject + Verb order", "L'interrogation indirecte reprend l'ordre affirmatif SVO."),
            ("Which words introduce yes/no indirect questions?", ["if / whether", "what / which", "why / how", "who / whom"], "if / whether", "if et whether introduisent les questions fermées indirectes."),
            ("Complete: 'Can you tell me how long the migration ___?'", ["will take", "will it take", "it will take to", "does it take"], "will take", "how long the migration will take."),
            ("What verb form follows 'Would you mind...' in polite requests?", ["Gerund (-ing form)", "Bare infinitive", "Past participle", "Full infinitive with to"], "Gerund (-ing form)", "Would you mind + V-ing.")
        ],
        "practice": [
            ("Convert the direct question 'Where are the logs?' into a polite indirect request:", ["Could you please let us know where the application logs are located?", "Could you please let us know where are located the application logs?", "Could you please let us know where are the application logs located?", "Could you please let us know where did the application logs locate?"], "Could you please let us know where the application logs are located?", "Question indirecte courtoise SVO."),
            ("Ask a vendor if their API supports rate-limiting webhooks:", ["Could you clarify whether your API supports rate-limiting webhook notifications?", "Could you clarify does your API support rate-limiting webhook notifications?", "Could you clarify supports your API rate-limiting webhook notifications?", "Could you clarify is your API support rate-limiting webhook notifications?"], "Could you clarify whether your API supports rate-limiting webhook notifications?", "whether + subject + verb."),
            ("Inquire about an outage timeline diplomatically:", ["Do you happen to know when the primary database cluster will be fully restored?", "Do you happen to know when will be fully restored the primary database cluster?", "Do you happen to know when will the primary database cluster be fully restored?", "Do you happen to know when does the primary database cluster be fully restored?"], "Do you happen to know when the primary database cluster will be fully restored?", "when + subject + will be restored."),
            ("Request the root cause analysis document from a cloud vendor:", ["I was wondering if you could provide the preliminary root cause analysis report for yesterday's outage.", "I was wondering could you provide the preliminary root cause analysis report for yesterday's outage?", "I was wondering if could you provide the preliminary root cause analysis report for yesterday's outage.", "I was wondering whether could you provide the preliminary root cause analysis report for yesterday's outage."], "I was wondering if you could provide the preliminary root cause analysis report for yesterday's outage.", "I was wondering if you could provide...")
        ]
    },

    142: {
        "title": "Third Conditional: Root Cause Analysis",
        "questions": [
            ("Choose the correct Third Conditional structure for a past post-mortem scenario:", ["If we had enabled automated connection pooling, the database would not have crashed under load.", "If we enabled automated connection pooling, the database would not crash under load.", "If we had enable automated connection pooling, the database would not had crashed under load.", "If we would have enabled automated connection pooling, the database had not crashed under load."], "If we had enabled automated connection pooling, the database would not have crashed under load.", "3ème conditionnel : If + had + Participe passé, would have + Participe passé."),
            ("Select the sentence expressing an unrealized past safeguard in an RCA:", ["If the monitoring alerts had triggered earlier, our on-call engineers could have mitigated the memory leak sooner.", "If the monitoring alerts triggered earlier, our on-call engineers could mitigate the memory leak sooner.", "If the monitoring alerts would have triggered earlier, our on-call engineers had mitigated the memory leak sooner.", "If the monitoring alerts have triggered earlier, our on-call engineers would mitigate the memory leak sooner."], "If the monitoring alerts had triggered earlier, our on-call engineers could have mitigated the memory leak sooner.", "could have mitigated."),
            ("Complete the post-mortem analysis: 'The data loss ___ prevented if the snapshot schedule had run as configured.'", ["would have been", "would be", "had been", "will have been"], "would have been", "would have been prevented."),
            ("Choose the formal inversion without 'If' in technical post-mortems:", ["Had we implemented circuit breakers, the cascading failure would have been prevented.", "If had we implemented circuit breakers, the cascading failure would have been prevented.", "Were we implemented circuit breakers, the cascading failure would have been prevented.", "Did we implement circuit breakers, the cascading failure would have been prevented."], "Had we implemented circuit breakers, the cascading failure would have been prevented.", "Inversion formelle du 3e conditionnel : Had + Sujet + Participe passé."),
            ("Select the sentence analyzing root cause dependencies in past time:", ["If the staging environment had mirrored production data volume, we would have detected the index regression before release.", "If the staging environment mirrored production data volume, we detected the index regression before release.", "If the staging environment would mirror production data volume, we would have detected the index regression before release.", "If the staging environment had mirror production data volume, we had detected the index regression before release."], "If the staging environment had mirrored production data volume, we would have detected the index regression before release.", "had mirrored ... would have detected."),
            ("Complete: 'The outage ___ escalated into a Severity-1 incident if the primary node had failed over automatically.'", ["would not have", "had not", "will not have", "did not have"], "would not have", "would not have escalated."),
            ("Choose the formal conditional deduction: 'Had the secret key been rotated on schedule, the compromised credential ___ useless to the attacker.'", ["would have been", "would be", "had been", "was being"], "would have been", "Had the key been rotated ... would have been useless."),
            ("Complete: 'If we ___ the load test on the actual release candidate, we would have caught the deadlock.'", ["had executed", "executed", "would execute", "have executed"], "had executed", "had executed."),
            ("Select the sentence evaluating alternative architectural choices in the past:", ["If we had adopted an event-driven architecture earlier, the microservices would have decoupled more cleanly during the peak event.", "If we adopted an event-driven architecture earlier, the microservices would decouple more cleanly during the peak event.", "If we would adopt an event-driven architecture earlier, the microservices had decoupled more cleanly during the peak event.", "If we had adopt an event-driven architecture earlier, the microservices would have decouple more cleanly during the peak event."], "If we had adopted an event-driven architecture earlier, the microservices would have decoupled more cleanly during the peak event.", "had adopted ... would have decoupled."),
            ("Complete: 'The customer impact would have been minimal if the fallback cache ___ populated.'", ["had been", "was", "would have been", "has been"], "had been", "if the cache had been populated."),
            ("Choose the Third Conditional question for an RCA review: 'Would the cluster have recovered faster if we had provisioned additional worker nodes?'", ["Would the cluster have recovered faster if we had provisioned additional worker nodes?", "Would the cluster recover faster if we had provisioned additional worker nodes?", "Had the cluster recovered faster if we provisioned additional worker nodes?", "Did the cluster recover faster if we would have provisioned additional worker nodes?"], "Would the cluster have recovered faster if we had provisioned additional worker nodes?", "Would the cluster have recovered...?")
        ],
        "quiz": [
            ("What is the formula for the Third Conditional in Root Cause Analysis (RCA)?", ["If + Past Perfect (had + V-ed), would/could/might have + Past Participle", "If + Past Simple, would + base verb", "If + Present Simple, will + base verb", "If + Past Perfect, will have + V-ed"], "If + Past Perfect (had + V-ed), would/could/might have + Past Participle", "If + had + participe passé, would have + participe passé."),
            ("How do you form the formal inversion of 'If we had known'?", ["Had we known", "Were we known", "Did we have known", "If had we known"], "Had we known", "Inversion sans 'if' : Had + Sujet + Participe passé."),
            ("Complete: 'If the firewall rules ___ updated, the unauthorized ingress would have been blocked.'", ["had been", "were", "would have been", "have been"], "had been", "had been updated."),
            ("What does the Third Conditional express in post-mortems?", ["A hypothetical past situation that did not happen and its imagined past consequence", "A present permanent truth", "A future roadmap commitment", "A daily operational routine"], "A hypothetical past situation that did not happen and its imagined past consequence", "Analyse rétrospective d'un scénario contrefactuel dans le passé.")
        ],
        "practice": [
            ("Analyze an unmitigated database outage using the Third Conditional:", ["If the automated failover mechanism had functioned properly, the API downtime would have been limited to under thirty seconds.", "If the automated failover mechanism functioned properly, the API downtime would be limited to under thirty seconds.", "If the automated failover mechanism would function properly, the API downtime had been limited to under thirty seconds.", "If the automated failover mechanism had functioned properly, the API downtime was limited to under thirty seconds."], "If the automated failover mechanism had functioned properly, the API downtime would have been limited to under thirty seconds.", "had functioned ... would have been limited."),
            ("Write a formal RCA sentence using conditional inversion (Had we...):", ["Had we performed end-to-end load testing on the staging cluster, this deadlock would have been identified prior to release.", "Had we perform end-to-end load testing on the staging cluster, this deadlock would have been identified prior to release.", "If had we performed end-to-end load testing on the staging cluster, this deadlock would have been identified prior to release.", "Were we performed end-to-end load testing on the staging cluster, this deadlock would have been identified prior to release."], "Had we performed end-to-end load testing on the staging cluster, this deadlock would have been identified prior to release.", "Had we performed..."),
            ("Hypothesize regarding monitoring detection speed in a post-mortem:", ["The on-call team could have intervened twenty minutes earlier if the PagerDuty threshold had been configured properly.", "The on-call team could intervene twenty minutes earlier if the PagerDuty threshold was configured properly.", "The on-call team can have intervened twenty minutes earlier if the PagerDuty threshold would be configured properly.", "The on-call team could have intervened twenty minutes earlier if the PagerDuty threshold had configure properly."], "The on-call team could have intervened twenty minutes earlier if the PagerDuty threshold had been configured properly.", "could have intervened..."),
            ("Evaluate an unapplied security patch in a vulnerability review:", ["If the infrastructure team had applied the OpenSSL patch on Monday, the vulnerability would not have been exposed during the scan.", "If the infrastructure team applied the OpenSSL patch on Monday, the vulnerability would not be exposed during the scan.", "If the infrastructure team would have applied the OpenSSL patch on Monday, the vulnerability had not been exposed during the scan.", "If the infrastructure team had applied the OpenSSL patch on Monday, the vulnerability was not exposed during the scan."], "If the infrastructure team had applied the OpenSSL patch on Monday, the vulnerability would not have been exposed during the scan.", "had applied ... would not have been exposed.")
        ]
    },

    143: {
        "title": "Gerund vs Infinitive in Technical Writing",
        "questions": [
            ("Choose the verb requiring a gerund (-ing): 'We strongly recommend ___ automated vulnerability scans on all container images.'", ["running", "to run", "run", "to running"], "running", "'recommend' est suivi d'un gérondif."),
            ("Select the verb requiring an infinitive: 'The engineering team aims ___ zero downtime during the database migration.'", ["to achieve", "achieving", "achieve", "to achieving"], "to achieve", "'aim' est suivi de l'infinitif complet."),
            ("Complete: 'Developers must avoid ___ API secrets directly in client-side code.'", ["hardcoding", "to hardcode", "hardcode", "to hardcoding"], "hardcoding", "'avoid' est suivi d'un gérondif."),
            ("Choose the verb taking an infinitive: 'The architecture committee decided ___ gRPC for all internal service communication.'", ["to adopt", "adopting", "adopt", "to adopting"], "to adopt", "'decide' prend to + infinitif."),
            ("Select the preposition requiring a gerund: 'You can optimize query latency by ___ composite indexes on searched columns.'", ["creating", "to create", "create", "to creating"], "creating", "by + gérondif."),
            ("Complete: 'The application failed ___ the database connection pool within the 30-second timeout.'", ["to initialize", "initializing", "initialize", "to initializing"], "to initialize", "'fail' est suivi de l'infinitif."),
            ("Choose the gerund as subject in a technical paper: '___ distributed tracing simplifies root cause analysis in microservices.'", ["Implementing", "To implement", "Implement", "Implemented"], "Implementing", "Gérondif en position sujet."),
            ("Complete: 'We cannot afford ___ deployment testing before launching to production.'", ["to skip", "skipping", "skip", "to skipping"], "to skip", "afford to skip."),
            ("Select the verb taking a gerund: 'The system administrator finished ___ the staging nodes with the latest kernel.'", ["patching", "to patch", "patch", "to patching"], "patching", "finished patching."),
            ("Complete: 'Our objective is ___ automated canary rollouts for all core services.'", ["to enable", "enabling", "enable", "to enabling"], "to enable", "is to enable."),
            ("Choose the sentence with correct verb complementation: 'We suggest migrating to OpenTelemetry rather than continuing with legacy agents.'", ["We suggest migrating to OpenTelemetry rather than continuing with legacy agents.", "We suggest to migrate to OpenTelemetry rather than to continue with legacy agents.", "We suggest migrate to OpenTelemetry rather than continue with legacy agents.", "We suggest for migrating to OpenTelemetry rather than continue with legacy agents."], "We suggest migrating to OpenTelemetry rather than continuing with legacy agents.", "suggest migrating."),
            ("Complete: 'The script was designed for ___ orphan cloud resources automatically.'", ["identifying", "to identify", "identify", "to identifying"], "identifying", "for + gérondif.")
        ],
        "quiz": [
            ("Which of these technical verbs is followed by a Gerund (-ing)?", ["avoid / recommend / suggest / consider / finish", "aim / decide / refuse / fail / hope", "want / need to / wish", "plan / promise"], "avoid / recommend / suggest / consider / finish", "Ces verbes requièrent un gérondif."),
            ("Which form must follow prepositions like 'by', 'without', 'after', 'for'?", ["Gerund (-ing)", "Infinitive with 'to'", "Bare infinitive", "Past participle"], "Gerund (-ing)", "Les prépositions sont toujours suivies d'un gérondif."),
            ("Complete: 'We plan ___ the new Redis cluster on Tuesday.'", ["to deploy", "deploying", "deploy", "to deploying"], "to deploy", "plan + to deploy."),
            ("Complete: 'You can prevent SQL injections by ___ prepared statements.'", ["using", "to use", "use", "to using"], "using", "by + using.")
        ],
        "practice": [
            ("Formulate a security recommendation in an architecture specification:", ["We recommend implementing Mutual TLS (mTLS) to encrypt all service-to-service communication.", "We recommend to implement Mutual TLS (mTLS) to encrypt all service-to-service communication.", "We recommend implement Mutual TLS (mTLS) to encrypt all service-to-service communication.", "We recommend for implementing Mutual TLS (mTLS) to encrypt all service-to-service communication."], "We recommend implementing Mutual TLS (mTLS) to encrypt all service-to-service communication.", "recommend implementing."),
            ("State a technical goal using an infinitive structure:", ["Our primary engineering objective for Q3 is to achieve 99.99% availability across all APIs.", "Our primary engineering objective for Q3 is achieving 99.99% availability across all APIs.", "Our primary engineering objective for Q3 is achieve 99.99% availability across all APIs.", "Our primary engineering objective for Q3 is for achieving 99.99% availability across all APIs."], "Our primary engineering objective for Q3 is to achieve 99.99% availability across all APIs.", "is to achieve."),
            ("Advise against a risky development anti-pattern:", ["Developers should avoid committing unencrypted environment variables to public repositories.", "Developers should avoid to commit unencrypted environment variables to public repositories.", "Developers should avoid commit unencrypted environment variables to public repositories.", "Developers should avoid for committing unencrypted environment variables to public repositories."], "Developers should avoid committing unencrypted environment variables to public repositories.", "avoid committing."),
            ("Explain the mechanism of a performance optimization using a prepositional gerund:", ["You can drastically reduce database load by caching serialized JSON payloads in Redis.", "You can drastically reduce database load by to cache serialized JSON payloads in Redis.", "You can drastically reduce database load by cache serialized JSON payloads in Redis.", "You can drastically reduce database load by to caching serialized JSON payloads in Redis."], "You can drastically reduce database load by caching serialized JSON payloads in Redis.", "by caching.")
        ]
    },

    144: {
        "title": "Relative Clauses in System Documentation",
        "questions": [
            ("Choose the defining relative pronoun for a technical tool: 'We deployed a service mesh ___ routes traffic based on HTTP headers.'", ["that / which", "who", "whom", "where"], "that / which", "'that' ou 'which' pour des outils techniques."),
            ("Select the non-defining relative clause requiring commas: 'Envoy, ___ is an open-source edge proxy, handles all ingress routing.'", ["which", "that", "who", "where"], "which", "Propositions relatives explicatives (entre virgules) = 'which'."),
            ("Complete for a physical or logical location: 'The datacenter ___ our primary database resides has redundant power feeds.'", ["where", "which", "that", "whose"], "where", "'where' pour le lieu."),
            ("Choose the relative pronoun indicating ownership/attribution: 'We alerted the developer ___ pull request introduced the memory leak.'", ["whose", "who's", "whom", "which"], "whose", "'whose' exprime la possession/attribution relative."),
            ("Select the pronoun referring to human engineers/roles: 'The SRE ___ is on call must acknowledge the PagerDuty alert within five minutes.'", ["who", "which", "whose", "where"], "who", "'who' pour un être humain."),
            ("Complete: 'The vulnerability, ___ was discovered during the penetration test, has been remediated.'", ["which", "that", "where", "who"], "which", "which entre virgules."),
            ("Choose the sentence correctly distinguishing defining from non-defining relative clauses:", ["The servers that run Ubuntu 20.04 require patching, whereas Server 1, which runs Debian, is up to date.", "The servers which run Ubuntu 20.04 require patching, whereas Server 1 that runs Debian, is up to date.", "The servers who run Ubuntu 20.04 require patching, whereas Server 1 where runs Debian, is up to date.", "The servers whose run Ubuntu 20.04 require patching, whereas Server 1 which runs Debian is up to date."], "The servers that run Ubuntu 20.04 require patching, whereas Server 1, which runs Debian, is up to date.", "that restrictif vs which explicatif."),
            ("Complete: 'This document describes the API endpoints ___ require JWT authentication.'", ["that", "who", "whom", "whose"], "that", "that require JWT."),
            ("Select the sentence with omitted relative pronoun: 'The configuration file we edited yesterday resolved the port conflict.'", ["The configuration file we edited yesterday resolved the port conflict.", "The configuration file what we edited yesterday resolved the port conflict.", "The configuration file who we edited yesterday resolved the port conflict.", "The configuration file where we edited yesterday resolved the port conflict."], "The configuration file we edited yesterday resolved the port conflict.", "Omission du pronom relatif objet."),
            ("Complete: 'The cluster administrator, ___ credentials were compromised, revoked the active tokens.'", ["whose", "who", "which", "whom"], "whose", "whose credentials."),
            ("Choose the relative clause indicating a time period: 'October 15th was the date ___ the new microservice was deployed.'", ["when", "which", "where", "whose"], "when", "'when' pour le repère temporel.")
        ],
        "quiz": [
            ("What is the difference between 'that' and 'which' in relative clauses?", ["'that' is used in restrictive/defining clauses without commas; 'which' is used in non-restrictive clauses with commas", "'that' is only for humans; 'which' is for animals", "They are 100% interchangeable in all punctuation styles", "Neither can refer to software"], "'that' is used in restrictive/defining clauses without commas; 'which' is used in non-restrictive clauses with commas", "that = restrictive (sans virgule) ; which = non restrictive (avec virgules)."),
            ("Which relative pronoun indicates possession or attribution?", ["whose", "who's", "which", "whom"], "whose", "whose exprime la possession."),
            ("Complete: 'The load balancer, ___ was configured by DevOps, distributes ingress traffic.'", ["which", "that", "who", "whose"], "which", "which entre virgules."),
            ("Which relative pronoun is used for locations like VPCs, subnets, and datacenters?", ["where", "when", "who", "whose"], "where", "where pour les lieux physiques et logiques.")
        ],
        "practice": [
            ("Define the specific scope of an architectural component using a restrictive clause:", ["The ingress controller routes only requests that contain a valid Authorization bearer token.", "The ingress controller routes only requests, that contain a valid Authorization bearer token.", "The ingress controller routes only requests who contain a valid Authorization bearer token.", "The ingress controller routes only requests whose contain a valid Authorization bearer token."], "The ingress controller routes only requests that contain a valid Authorization bearer token.", "that restrictive sans virgule."),
            ("Add non-essential contextual detail using non-restrictive 'which':", ["PostgreSQL 16, which introduces significant query parallelization improvements, is now our default engine.", "PostgreSQL 16 that introduces significant query parallelization improvements is now our default engine.", "PostgreSQL 16 who introduces significant query parallelization improvements, is now our default engine.", "PostgreSQL 16 whose introduces significant query parallelization improvements is now our default engine."], "PostgreSQL 16, which introduces significant query parallelization improvements, is now our default engine.", ", which ... ,"),
            ("Identify the owner of a service in a technical runbook:", ["The platform team, whose on-call rotation handles tier-1 escalations, maintains the shared Redis cluster.", "The platform team, who's on-call rotation handles tier-1 escalations, maintains the shared Redis cluster.", "The platform team, which on-call rotation handles tier-1 escalations, maintains the shared Redis cluster.", "The platform team, who on-call rotation handles tier-1 escalations, maintains the shared Redis cluster."], "The platform team, whose on-call rotation handles tier-1 escalations, maintains the shared Redis cluster.", "whose on-call rotation."),
            ("Specify the hosting region of a database instance:", ["We migrated the replica to the Frankfurt region, where low-latency transit is guaranteed.", "We migrated the replica to the Frankfurt region, which low-latency transit is guaranteed.", "We migrated the replica to the Frankfurt region, that low-latency transit is guaranteed.", "We migrated the replica to the Frankfurt region, who low-latency transit is guaranteed."], "We migrated the replica to the Frankfurt region, where low-latency transit is guaranteed.", "where low-latency transit...")
        ]
    },

    145: {
        "title": "Comparing Architecture Styles: Monolith vs Microservices",
        "questions": [
            ("Choose the term describing strong dependency between components: 'In tightly ___ systems, modifying one module frequently breaks downstream dependencies.'", ["coupled", "isolated", "decoupled", "segregated"], "coupled", "'tightly coupled' (fortement couplé)."),
            ("Select the advantage of microservices architecture: 'Independent deployability allows teams to ship features without coordinating a monolithic ___.'", ["release train", "single file", "binary halt", "code freeze"], "release train", "'release train' (train de versions unifié)."),
            ("Complete the architecture comparison: 'While a monolith offers simpler local debugging, microservices provide superior ___ scalability.'", ["horizontal", "vertical", "monolithic", "centralized"], "horizontal", "'horizontal scalability' (mise à l'échelle horizontale)."),
            ("Choose the concept defining clean domain boundaries in Domain-Driven Design (DDD): 'Each microservice must govern its own ___ context.'", ["bounded", "infinite", "open", "mixed"], "bounded", "'bounded context' (contexte délimité)."),
            ("Select the architectural tradeoff: 'Decomposing a monolith into microservices trades in-process memory calls for network ___.'", ["latency and failure modes", "zero overhead", "perfect speed", "simple debugging"], "latency and failure modes", "Remplacement des appels mémoire par des appels réseau avec latence."),
            ("Complete: 'Event-driven communication enables asynchronous ___ between distributed services.'", ["decoupling", "coupling", "locking", "blocking"], "decoupling", "asynchronous decoupling."),
            ("Choose the pattern mitigating distributed data consistency issues: 'Instead of distributed 2PC transactions, microservices typically adopt the ___ pattern.'", ["Saga", "Singleton", "Factory", "Monad"], "Saga", "Le pattern Saga coordonne des transactions distribuées avec compensation."),
            ("Complete: 'A modular monolith enforces strict package boundaries while sharing a single ___.'", ["runtime deployment unit", "database table", "thread pool", "CPU core"], "runtime deployment unit", "Unité de déploiement unique."),
            ("Select the sentence contrasting operational complexity:", ["Microservices increase operational overhead because each service requires independent CI/CD pipelines, monitoring, and telemetry.", "Microservices eliminate all operational overhead and require zero maintenance.", "Monoliths require much more Kubernetes clusters than microservices.", "There is no difference in operational complexity between monoliths and microservices."], "Microservices increase operational overhead because each service requires independent CI/CD pipelines, monitoring, and telemetry.", "Complexité opérationnelle accrue."),
            ("Complete: 'Database-per-service ensures that services do not share ___ at the persistence layer.'", ["schemas or tables", "networks", "operating systems", "IP addresses"], "schemas or tables", "Isolation des schémas de base de données."),
            ("Choose the concept describing service failure containment: 'We implemented bulkheads to prevent a failure in the recommendation engine from cascading to the core ___ service.'", ["checkout", "color", "font", "css"], "checkout", "Protection du service critique de paiement/checkout."),
            ("Complete the sentence: 'Microservices communicate externally through an API ___ that handles authentication and rate limiting.'", ["gateway", "portal", "tunnel", "bridge"], "gateway", "API gateway.")
        ],
        "quiz": [
            ("What does 'loose coupling' mean in distributed software architecture?", ["Components have minimal dependencies on each other and interact through stable, well-defined contracts", "Components share the exact same database tables", "All code is in a single repository", "Services cannot talk to each other"], "Components have minimal dependencies on each other and interact through stable, well-defined contracts", "Dépendances minimales via des contrats d'interface clairs."),
            ("What is the primary benefit of the 'Database-per-service' pattern?", ["It guarantees schema encapsulation and prevents tight database-level coupling between microservices", "It makes queries faster by 100x", "It eliminates the need for backups", "It reduces cloud costs to zero"], "It guarantees schema encapsulation and prevents tight database-level coupling between microservices", "Encapsulation des données et découplage fort."),
            ("Complete: 'The ___ pattern coordinates distributed transactions across multiple microservices.'", ["Saga", "Singleton", "Proxy", "Observer"], "Saga", "Le pattern Saga orchestre les transactions compensatoires."),
            ("Why do microservices require sophisticated distributed tracing tools like Jaeger or Zipkin?", ["Because an incoming user request traverses multiple distributed network hops across distinct microservices", "To compile Go code", "To encrypt hard drives", "To replace SQL databases"], "Because an incoming user request traverses multiple distributed network hops across distinct microservices", "Traçabilité des requêtes transverses multi-services.")
        ],
        "practice": [
            ("Articulate the rationale for migrating from a monolith to microservices in an ADR:", ["We are decomposing the monolithic billing engine into autonomous microservices to enable independent scaling and accelerate team deployment cadence.", "We are deleting the monolith because microservices are cooler.", "Monolith is old so we rewrite everything.", "Microservices fix all bugs automatically."], "We are decomposing the monolithic billing engine into autonomous microservices to enable independent scaling and accelerate team deployment cadence.", "Justification technique et organisationnelle rationnelle."),
            ("Highlight the architectural trade-offs of microservices in a design review:", ["While microservices provide fault isolation, they introduce significant distributed systems complexity, network latency, and eventual consistency challenges.", "Microservices have no downsides and solve all architecture issues.", "Microservices are simpler than monoliths in every aspect.", "Monoliths should never be used under any circumstances."], "While microservices provide fault isolation, they introduce significant distributed systems complexity, network latency, and eventual consistency challenges.", "Évaluation équilibrée des bénéfices et compromis."),
            ("Describe the role of an API Gateway in front of microservices:", ["The API Gateway acts as a single reverse-proxy entry point, handling TLS termination, JWT validation, and intelligent request routing to backend services.", "The API Gateway is just an extra server that does nothing.", "The API Gateway replaces all backend code.", "The API Gateway connects computers with cables."], "The API Gateway acts as a single reverse-proxy entry point, handling TLS termination, JWT validation, and intelligent request routing to backend services.", "Définition précise des responsabilités de l'API Gateway."),
            ("Propose a modular monolith as a pragmatic intermediate step:", ["Before committing to full microservices, we recommend adopting a modular monolith with strict domain boundaries to validate our service decomposition model.", "Let's build microservices immediately without planning.", "Modular monoliths are bad, avoid them.", "We refuse to structure our monolith."], "Before committing to full microservices, we recommend adopting a modular monolith with strict domain boundaries to validate our service decomposition model.", "Démarche d'architecture pragmatique et incrémentale.")
        ]
    }
}
