# -*- coding: utf-8 -*-
"""
Curriculum for Lessons 149 to 160 (End of Level 5 and Full Level 6)
12 lessons: 149(12), 150(11), 151(12), 152(11), 153(12), 154(11), 155(12), 156(11), 157(12), 158(11), 159(12), 160(11)
Total: 138 questions, 48 quizzes, 48 practices.
"""

CURRICULUM_149_160 = {
    149: {
        "title": "Negotiating SLA, RTO and RPO Commitments",
        "questions": [
            ("Choose the definition of Recovery Time Objective (RTO): 'RTO defines the maximum acceptable duration of ___ before service is restored.'", ["downtime", "data loss", "throughput", "bandwidth"], "downtime", "RTO mesure la durée maximale admissible d'interruption de service."),
            ("Select the definition of Recovery Point Objective (RPO): 'RPO specifies the maximum tolerable period of ___ during a disaster.'", ["data loss / rollback", "network latency", "downtime", "CPU throttling"], "data loss / rollback", "RPO mesure la perte maximale de données tolérable en temps."),
            ("Complete the Service Level Agreement (SLA) commitment: 'Our enterprise tier guarantees 99.99% availability, which equates to less than 5 minutes of ___ per month.'", ["unscheduled downtime", "total traffic", "maintenance", "backup time"], "unscheduled downtime", "'unscheduled downtime' (temps d'arrêt non planifié)."),
            ("Choose the term for contractual penalties: 'If uptime falls below the agreed SLO threshold, customers are entitled to service ___.'", ["credits", "refunds of code", "tokens of data", "servers"], "credits", "'service credits' (crédits de pénalité de service)."),
            ("Select the term distinguishing target from contract: 'While the SLA is the external legal contract, the ___ represents our internal engineering target.'", ["SLO (Service Level Objective)", "KPI", "RTO", "MTTR"], "SLO (Service Level Objective)", "SLO = objectif interne d'ingénierie ; SLA = engagement contractuel externe."),
            ("Complete: 'To achieve a 15-minute RPO, database backups must be replicated ___ across regions.'", ["asynchronously in near real-time", "monthly", "annually", "once a day"], "asynchronously in near real-time", "Réplication quasi temps réel nécessaire pour un RPO de 15 minutes."),
            ("Choose the term measuring incident recovery speed: 'Our Mean Time To ___ (MTTR) dropped to under 12 minutes following automated runbook adoption.'", ["Recover / Remediate", "Read", "Reboot", "Report"], "Recover / Remediate", "MTTR = Mean Time To Recover."),
            ("Complete: 'The contract includes an error ___ allowance of 0.01% of total monthly HTTP requests.'", ["budget", "margin of price", "limit of cost", "discount"], "budget", "error budget (budget d'erreur SRE)."),
            ("Select the clause defining planned maintenance: 'Scheduled maintenance windows are excluded from monthly ___ calculations provided 48 hours notice is given.'", ["availability / uptime", "downtime", "billing", "pricing"], "availability / uptime", "Exclusion des fenêtres de maintenance planifiée du calcul de disponibilité."),
            ("Complete: 'Failure to meet the agreed 4-hour RTO will trigger an automatic SLA ___ penalty.'", ["breach", "award", "gift", "bonus"], "breach", "SLA breach (violation d'engagement de service)."),
            ("Choose the negotiation phrasing for balancing SLA cost: 'Committing to five nines (99.999%) availability requires multi-region active-active architecture, which will ___ infrastructure costs.'", ["triple / substantially increase", "reduce", "eliminate", "halve"], "triple / substantially increase", "Impact financier direct des 5 neufs."),
            ("Complete the formal commitment: 'The vendor agrees to maintain a 24/7/365 dedicated response team for Severity-1 ___.'", ["incidents / escalations", "questions", "feedback", "chatting"], "incidents / escalations", "Engagement de support 24/7/365.")
        ],
        "quiz": [
            ("What is the fundamental difference between RTO and RPO?", ["RTO measures acceptable downtime duration; RPO measures acceptable data loss time window", "RTO is for money; RPO is for servers", "RTO and RPO are identical acronyms", "RTO is internal; RPO is external"], "RTO measures acceptable downtime duration; RPO measures acceptable data loss time window", "RTO = temps d'arrêt max ; RPO = perte de données max."),
            ("What is an 'Error Budget' in Site Reliability Engineering (SRE)?", ["The allowable threshold of unreliability (e.g. 0.01% errors) that a service can accumulate before deployments are frozen", "The money spent on bugs", "The salary of QA engineers", "A penalty paid to cloud providers"], "The allowable threshold of unreliability (e.g. 0.01% errors) that a service can accumulate before deployments are frozen", "Quota d'erreurs admissible avant blocage des livraisons."),
            ("Complete: '99.9% uptime is commonly referred to as ___ nines.'", ["three", "two", "four", "five"], "three", "Three nines (trois neufs)."),
            ("What does 'SLO' stand for?", ["Service Level Objective", "System Load Operator", "Standard Log Output", "Software License Option"], "Service Level Objective", "Service Level Objective (objectif interne).")
        ],
        "practice": [
            ("Formulate an SLA commitment clause in a Master Service Agreement:", ["The Provider guarantees 99.95% monthly service availability; failure to meet this SLO results in a 10% monthly service credit.", "We promise the server will work mostly all month.", "If the website dies, we will give you some money back.", "Uptime is 100% or we apologize."], "The Provider guarantees 99.95% monthly service availability; failure to meet this SLO results in a 10% monthly service credit.", "Clause contractuelle précise et chiffrée."),
            ("Define disaster recovery RTO and RPO targets in an enterprise architecture spec:", ["Disaster Recovery Targets: RTO = 1 hour (complete service recovery); RPO = 5 minutes (maximum permissible data rollback).", "Disaster Recovery Targets: Fix it as fast as possible with minimal lost data.", "Disaster Recovery Targets: RTO is 1 day, RPO is 1 month.", "Disaster Recovery Targets: No downtime ever allowed."], "Disaster Recovery Targets: RTO = 1 hour (complete service recovery); RPO = 5 minutes (maximum permissible data rollback).", "Spécification technique RTO/RPO formelle."),
            ("Negotiate realistic SLA boundaries with an enterprise customer:", ["While we understand your preference for 99.999% uptime, achieving five nines requires dedicated active-active multi-region infrastructure at three times the standard pricing tier.", "99.999% is impossible, you can't have it.", "Five nines is too expensive, pick something else.", "We don't do five nines."], "While we understand your preference for 99.999% uptime, achieving five nines requires dedicated active-active multi-region infrastructure at three times the standard pricing tier.", "Négociation commerciale et technique équilibrée."),
            ("Document error budget burn rate in an SRE weekly review:", ["Our 30-day error budget consumed 42% of its allowance following Tuesday's DNS propagation delay; new feature rollouts remain permitted.", "Error budget is going down because of DNS.", "We wasted error budget on Tuesday.", "Errors happened on Tuesday."], "Our 30-day error budget consumed 42% of its allowance following Tuesday's DNS propagation delay; new feature rollouts remain permitted.", "Rapport de consommation de budget d'erreur SRE.")
        ]
    },

    150: {
        "title": "Writing Incident Timelines and RCA Reports",
        "questions": [
            ("Choose the professional phrase defining detection delta in a timeline: 'Detection Delta: The outage began at 04:12 UTC and was ___ by automated monitors at 04:15 UTC.'", ["detected / flagged", "ignored", "deleted", "fixed"], "detected / flagged", "Horodatage précis de détection."),
            ("Select the section heading for identifying systemic contributing factors:", ["Root Cause and Contributing Factors", "Who is to blame for the bug", "Why engineers failed", "Mistakes made by staff"], "Root Cause and Contributing Factors", "Titre canonique d'analyse causale."),
            ("Complete the blameless post-mortem commitment: 'This post-mortem is conducted under a blameless culture to identify ___ improvements rather than individual fault.'", ["systemic / process", "personal", "disciplinary", "punitive"], "systemic / process", "Focus sur les améliorations systémiques."),
            ("Choose the phrase describing temporary triage action: 'Interim Mitigation: Traffic was ___ to the standby cluster while root-cause debugging proceeded.'", ["diverted / rerouted", "destroyed", "abandoned", "halted permanently"], "diverted / rerouted", "Mesure conservatoire intermédiaire."),
            ("Select the accurate timestamp formatting for international post-mortems:", ["2026-08-31 14:22:00 UTC", "Aug 31 at around 2 PM my time", "Yesterday afternoon", "14:22 local"], "2026-08-31 14:22:00 UTC", "Norme ISO 8601 en heure universelle UTC."),
            ("Complete: 'The Mean Time to Detect (MTTD) for this incident was ___ minutes.'", ["three", "three o'clock", "three times", "third"], "three", "MTTD = Mean Time to Detect."),
            ("Choose the phrase describing permanent remediation: 'Permanent Corrective Action: Implemented automated schema validation in the CI/CD pipeline to prevent ___ of this defect.'", ["recurrence", "memory", "rollback", "reboot"], "recurrence", "prevent recurrence (empêcher la réapparition)."),
            ("Complete: 'The blast radius was ___ strictly to the EU-West payment microservice.'", ["confined / restricted", "blown up", "destroyed", "unlimited"], "confined / restricted", "confined to (circonscrit à)."),
            ("Select the phrase documenting the resolution timestamp: 'Full service restoration was achieved at 15:45 UTC after verifying database replication integrity.'", ["Full service restoration was achieved at 15:45 UTC after verifying database replication integrity.", "Everything was fixed at 15:45 and we went home.", "The bug stopped existing at 15:45.", "At 15:45 we finished the repair."], "Full service restoration was achieved at 15:45 UTC after verifying database replication integrity.", "Formulation formelle de fin d'incident."),
            ("Complete: 'A post-incident review meeting is scheduled for Thursday to assign ownership of the five ___ items.'", ["action", "talking", "blaming", "worrying"], "action", "action items (actions correctives)."),
            ("Choose the closing summary sentence of a formal RCA document: 'By addressing these architectural vulnerabilities, we will significantly enhance platform resilience against similar failure modes.'", ["By addressing these architectural vulnerabilities, we will significantly enhance platform resilience against similar failure modes.", "We hope this never happens again.", "Outage is resolved, document closed.", "No more comments."], "By addressing these architectural vulnerabilities, we will significantly enhance platform resilience against similar failure modes.", "Conclusion tournée vers la résilience future.")
        ],
        "quiz": [
            ("What does 'MTTD' stand for in incident chronology?", ["Mean Time To Detect", "Maximum Transaction Total Daily", "Memory Thread Trace Dump", "Multi-Tenant Traffic Director"], "Mean Time To Detect", "Temps moyen de détection."),
            ("Why must all timestamps in global incident reports be written in UTC?", ["To avoid confusion across distributed engineering teams in different time zones", "Because servers only know UTC", "To comply with local traffic laws", "To make time calculations harder"], "To avoid confusion across distributed engineering teams in different time zones", "L'UTC harmonise la chronologie entre toutes les équipes mondiales."),
            ("Complete: 'Blast ___ defines the scope and boundary of systems impacted by an incident.'", ["radius", "area", "zone", "circle"], "radius", "Blast radius (rayon d'impact)."),
            ("What is the primary objective of a Root Cause Analysis (RCA)?", ["To understand how and why a failure occurred and implement systemic preventative safeguards", "To assign financial penalties to employees", "To fire junior developers", "To delete the failing code entirely"], "To understand how and why a failure occurred and implement systemic preventative safeguards", "Comprendre les causes profondes et mettre en place des garde-fous durables.")
        ],
        "practice": [
            ("Write a precise, UTC-timestamped timeline entry for a post-mortem report:", ["14:15:30 UTC — PagerDuty alert fired: High HTTP 500 error rate on payment-gateway (>5% threshold).", "At 2:15 PM alert happened because of 500 errors.", "14:15 — Something broke in payment.", "Payment alert triggered around 14:15."], "14:15:30 UTC — PagerDuty alert fired: High HTTP 500 error rate on payment-gateway (>5% threshold).", "Ligne de chronologie normalisée et précise."),
            ("Document the root cause mechanism factually in an RCA report:", ["Root Cause: A race condition in the connection pool initialization allowed worker threads to execute queries prior to TLS handshake completion.", "Root Cause: Developer wrote bad code for connection pool.", "Root Cause: Database didn't want to connect.", "Root Cause: Connection pool died unexpectedly."], "Root Cause: A race condition in the connection pool initialization allowed worker threads to execute queries prior to TLS handshake completion.", "Explication technique détaillée du mécanisme de défaillance."),
            ("State the blast radius and customer impact in a blameless tone:", ["Impact Summary: The incident affected 2.1% of EU transactions between 14:15 and 14:42 UTC; zero data corruption or financial discrepancies were detected.", "Impact Summary: Lots of EU users were angry for 30 minutes.", "Impact Summary: Payment was down in EU.", "Impact Summary: Bad experience for EU customers."], "Impact Summary: The incident affected 2.1% of EU transactions between 14:15 and 14:42 UTC; zero data corruption or financial discrepancies were detected.", "Bilan d'impact quantifié et mesuré."),
            ("Formulate an actionable preventative corrective action with an owner:", ["Action Item: Implement automated circuit breaking in payment-service (Owner: @maria, Due: Sprint 42).", "Action Item: Make payment service better (Owner: Team).", "Action Item: Don't break connection pool again.", "Action Item: Fix bugs."], "Action Item: Implement automated circuit breaking in payment-service (Owner: @maria, Due: Sprint 42).", "Action SMART (Spécifique, Mesurable, Attribuable, Réaliste, Temporelle).")
        ]
    },

    151: {
        "title": "Describing Infrastructure as Code (IaC) with Terraform",
        "questions": [
            ("Choose the term describing declarative configuration state: 'Terraform compares your desired state with the actual infrastructure recorded in the ___ file.'", ["terraform.tfstate", "index.html", "package.json", "Dockerfile"], "terraform.tfstate", "Le fichier tfstate enregistre l'état réel de l'infrastructure."),
            ("Select the command used to preview infrastructure changes before execution: 'Always run ___ to inspect execution plans prior to applying changes.'", ["terraform plan", "terraform apply", "terraform destroy", "terraform init"], "terraform plan", "'terraform plan' prévisualise les modifications prévues."),
            ("Complete the IaC concept: 'Infrastructure as Code ensures that cloud environments are ___ and reproducible.'", ["declarative / deterministic", "random", "manual", "unpredictable"], "declarative / deterministic", "Caractère déclaratif et déterministe de l'IaC."),
            ("Choose the term for configuration drift: 'When manual changes are made in the AWS console, the state experiences ___.'", ["drift", "decay", "rotation", "compilation"], "drift", "State drift (dérive de configuration par rapport au code)."),
            ("Select the keyword defining reusable infrastructure components: 'We packaged our VPC networking architecture into a reusable Terraform ___.'", ["module", "function", "class", "plugin"], "module", "Terraform module (module réutilisable)."),
            ("Complete: 'To store state files securely in team environments, configure a remote ___ in Amazon S3 with DynamoDB state locking.'", ["backend", "frontend", "server", "compiler"], "backend", "Remote backend (S3 + DynamoDB locking)."),
            ("Choose the command that applies the infrastructure modifications: 'Execute ___ with automated approval in the CI pipeline.'", ["terraform apply -auto-approve", "terraform plan -force", "terraform init -run", "terraform validate -go"], "terraform apply -auto-approve", "'terraform apply -auto-approve' applique les modifications en CI."),
            ("Complete: 'Terraform uses the HashiCorp Configuration Language (___) for defining resources.'", ["HCL", "HTML", "YAML", "XML"], "HCL", "HCL = HashiCorp Configuration Language."),
            ("Select the principle of idempotent execution: 'An idempotent Terraform run produces ___ changes when the infrastructure matches the code.'", ["zero / no", "random", "duplicate", "infinite"], "zero / no", "L'idempotence garantit 0 modification si l'état désiré est déjà atteint."),
            ("Complete: 'Variables in Terraform allow engineers to ___ environment configurations between staging and production.'", ["parameterize", "hardcode", "delete", "encrypt"], "parameterize", "Paramétrage des environnements."),
            ("Choose the command validating syntax and configuration correctness: 'Run ___ to check for configuration errors without accessing remote APIs.'", ["terraform validate", "terraform destroy", "terraform apply", "terraform import"], "terraform validate", "'terraform validate' vérifie la syntaxe."),
            ("Complete the IaC definition: '___ allows teams to version-control cloud infrastructure in Git repositories alongside application code.'", ["Infrastructure as Code (IaC)", "SSH scripting", "Manual clicking", "Hardware flashing"], "Infrastructure as Code (IaC)", "Définition de l'IaC.")
        ],
        "quiz": [
            ("What is 'state drift' in Terraform terminology?", ["The divergence between the actual live cloud infrastructure and the state recorded in Terraform code", "A slow network connection", "A deleted git branch", "A corrupted hard drive"], "The divergence between the actual live cloud infrastructure and the state recorded in Terraform code", "Dérive entre l'infrastructure réelle et le code Terraform."),
            ("What is the purpose of `terraform plan`?", ["To preview proposed infrastructure additions, modifications, and deletions before applying them", "To delete the cluster", "To format Python code", "To reboot the server"], "To preview proposed infrastructure additions, modifications, and deletions before applying them", "Prévisualisation des changements."),
            ("What storage mechanism prevents concurrent Terraform state modifications?", ["State locking (e.g. using DynamoDB or Terraform Cloud)", "Git commits", "File renaming", "Password protection"], "State locking (e.g. using DynamoDB or Terraform Cloud)", "Verrouillage d'état (State locking)."),
            ("Complete: 'Terraform resources are written in ___.'", ["HCL (HashiCorp Configuration Language)", "Python", "Bash", "Java"], "HCL (HashiCorp Configuration Language)", "HCL.")
        ],
        "practice": [
            ("Explain the benefits of remote backend state locking in an engineering guide:", ["Configuring an S3 remote backend with DynamoDB locking prevents race conditions and corrupted states during concurrent CI/CD pipeline runs.", "Remote state is good for saving files on the internet.", "DynamoDB makes Terraform fast.", "State files should be stored on developer laptops."], "Configuring an S3 remote backend with DynamoDB locking prevents race conditions and corrupted states during concurrent CI/CD pipeline runs.", "Explication claire du state locking."),
            ("Document the standard Terraform deployment workflow:", ["Standard IaC Workflow: 1. `terraform init` -> 2. `terraform validate` -> 3. `terraform plan` -> 4. Peer review -> 5. `terraform apply`.", "Workflow: Just run terraform apply directly in production.", "Workflow: Edit AWS console and write code later.", "Workflow: Delete state and re-create."], "Standard IaC Workflow: 1. `terraform init` -> 2. `terraform validate` -> 3. `terraform plan` -> 4. Peer review -> 5. `terraform apply`.", "Workflow Terraform professionnel étape par étape."),
            ("Describe a reusable Terraform module in an architecture catalog:", ["The `terraform-aws-vpc` module encapsulates subnets, route tables, and NAT gateways across three availability zones with customizable CIDR blocks.", "This module creates some networking stuff in AWS.", "Module for VPC in cloud.", "Terraform code that builds network."], "The `terraform-aws-vpc` module encapsulates subnets, route tables, and NAT gateways across three availability zones with customizable CIDR blocks.", "Description technique exhaustive de module IaC."),
            ("Explain how to remediate state drift detected during daily reconciliation:", ["When drift is detected, inspect the diff with `terraform plan` and either update the code to reflect intentional changes or run `terraform apply` to overwrite unauthorized manual edits.", "If drift happens, delete the cloud account.", "Ignore drift because code will fix itself.", "Never run terraform plan."], "When drift is detected, inspect the diff with `terraform plan` and either update the code to reflect intentional changes or run `terraform apply` to overwrite unauthorized manual edits.", "Protocole d'assainissement de dérive de configuration.")
        ]
    },

    152: {
        "title": "CI/CD Pipeline Automation Workflows",
        "questions": [
            ("Choose the deployment strategy minimizing downtime by running two identical environments: 'In a ___ deployment, traffic is switched from the green fleet to the blue fleet instantaneously.'", ["blue-green", "canary", "big-bang", "rolling"], "blue-green", "Blue-green deployment (bascule instantanée entre deux environnements identiques)."),
            ("Select the deployment pattern where a small percentage of users receives the new version first: 'A ___ deployment routes 5% of traffic to the new version to monitor telemetry before full rollout.'", ["canary", "blue-green", "shadow", "offline"], "canary", "Canary deployment (routage progressif de 5% du trafic)."),
            ("Complete the CI/CD pipeline stage definition: 'The build artifact must pass through automated linting, unit testing, and security ___ gates before deployment.'", ["validation / compliance", "destruction", "ignoring", "rebooting"], "validation / compliance", "Portes de validation et conformité en pipeline CI/CD."),
            ("Choose the term for deploying every merged commit automatically: 'Continuous ___ automatically releases verified artifacts directly to production.'", ["Deployment", "Integration", "Compilation", "Monitoring"], "Deployment", "Continuous Deployment (déploiement continu automatisé en production)."),
            ("Complete: 'A ___ trigger initiates the CI/CD pipeline whenever a pull request is merged into main.'", ["webhook / event", "manual button", "weekly cron", "hardware switch"], "webhook / event", "Déclenchement par webhook / événement Git."),
            ("Select the artifact repository used for storing compiled binaries or container images:", ["Registry (e.g. Harbor, ECR, Nexus)", "Git commit", "Slack channel", "Jira ticket"], "Registry (e.g. Harbor, ECR, Nexus)", "Container registry / gestionnaire d'artefacts."),
            ("Complete: 'If automated integration tests fail, the pipeline immediately ___ and blocks promotion.'", ["aborts / terminates", "continues", "deploys anyway", "deletes the repo"], "aborts / terminates", "Arrêt immédiat du pipeline en cas d'échec de test."),
            ("Choose the term for testing production traffic against a new build without returning responses to users: 'A ___ deployment mirrors live production requests to the candidate service.'", ["shadow / dark", "canary", "blue-green", "rolling"], "shadow / dark", "Shadow / Dark deployment (duplication silencieuse du trafic)."),
            ("Complete: 'Pipeline as Code allows engineering teams to define CI/CD workflows using declarative ___ files.'", ["YAML", "HTML", "Binary", "SQL"], "YAML", "Pipelines as Code déclaratifs en YAML (GitHub Actions, GitLab CI)."),
            ("Select the security practice of scanning container images for CVEs in CI: 'Automated vulnerability scanning with tools like Trivy is integrated into the ___ stage.'", ["pre-deployment / build", "post-mortem", "offline", "decommissioning"], "pre-deployment / build", "Scan de vulnérabilité amont dans le pipeline."),
            ("Complete: 'Automated ___ mechanisms revert the release if error rates exceed thresholds during canary testing.'", ["rollback", "compilation", "scaling", "deletion"], "rollback", "Automated rollback (retour arrière automatisé).")
        ],
        "quiz": [
            ("What is the core difference between Continuous Delivery and Continuous Deployment?", ["Continuous Delivery requires manual approval to release to production; Continuous Deployment deploys automatically without human intervention", "Continuous Delivery is for Java; Deployment is for Python", "They are identical acronyms", "Continuous Delivery does not run tests"], "Continuous Delivery requires manual approval to release to production; Continuous Deployment deploys automatically without human intervention", "Continuous Delivery = déploiement déclenché sur validation ; Continuous Deployment = 100% automatisé."),
            ("What is a 'Canary Deployment'?", ["Exposing a new software version to a small subset of real users (e.g. 5%) before rolling out to 100%", "Deploying software on yellow servers", "Testing software in bird habitats", "Canceling the release"], "Exposing a new software version to a small subset of real users (e.g. 5%) before rolling out to 100%", "Déploiement progressif à un sous-ensemble d'utilisateurs."),
            ("Complete: 'In Blue-Green deployments, the ___ environment is active while the other is standby.'", ["one", "broken", "offline", "untested"], "one", "Un environnement actif, l'autre en standby."),
            ("What is the purpose of a 'Quality Gate' in CI/CD pipelines?", ["Enforcing strict code quality, test coverage, and security criteria that must pass before artifact promotion", "Opening doors in the office", "Slowing down developers on purpose", "Counting lines of code"], "Enforcing strict code quality, test coverage, and security criteria that must pass before artifact promotion", "Porte de validation qualité et sécurité incontournable.")
        ],
        "practice": [
            ("Document a Canary Deployment release strategy in an engineering runbook:", ["Canary Strategy: Route 5% of production traffic to the new image for 10 minutes. If 5xx error rates remain under 0.01%, proceed to 25%, 50%, and 100% rollout.", "Canary Strategy: Deploy to some users and hope it works.", "Canary Strategy: Release on Friday and see if people complain.", "Canary Strategy: Switch all traffic immediately."], "Canary Strategy: Route 5% of production traffic to the new image for 10 minutes. If 5xx error rates remain under 0.01%, proceed to 25%, 50%, and 100% rollout.", "Stratégie de déploiement canari documentée et chiffrée."),
            ("Describe the role of security scanning in a CI pipeline definition:", ["Every pull request triggers automated static code analysis (SAST) and container vulnerability scanning; critical CVEs automatically fail the build.", "We scan for security when we have time.", "Security scanning is done once per year.", "Security is checked manually by developers."], "Every pull request triggers automated static code analysis (SAST) and container vulnerability scanning; critical CVEs automatically fail the build.", "Intégration DevSecOps en amont du pipeline."),
            ("Explain the mechanics of a Blue-Green deployment failover:", ["If health checks fail on the Green environment post-deployment, the load balancer instantaneously flips traffic back to the Blue environment with zero downtime.", "If Green fails, we delete all servers and start over.", "Blue-Green means we turn off computers when broken.", "Traffic is lost if Green fails."], "If health checks fail on the Green environment post-deployment, the load balancer instantaneously flips traffic back to the Blue environment with zero downtime.", "Mécanique de bascule instantanée sans interruption."),
            ("Specify automated rollback criteria in a pipeline configuration file:", ["Rollback Threshold: Automatically execute `helm rollback` if p99 latency exceeds 350ms or HTTP 500 error count exceeds 20 within the evaluation window.", "Rollback Threshold: Roll back if it seems slow.", "Rollback Threshold: Undo when user is mad.", "Rollback Threshold: No rollback needed."], "Rollback Threshold: Automatically execute `helm rollback` if p99 latency exceeds 350ms or HTTP 500 error count exceeds 20 within the evaluation window.", "Critères de rollback automatisés et mesurables.")
        ]
    }
}



CURRICULUM_149_160.update({
    153: {
        "title": "Containerization and Orchestration (Docker & K8s)",
        "questions": [
            ("Choose the Kubernetes resource managing stateless container replicas: 'A Kubernetes ___ ensures that a specified number of identical pod replicas are running.'", ["Deployment", "DaemonSet", "StatefulSet", "ConfigMap"], "Deployment", "Un Deployment Kubernetes gère les répliques de pods sans état."),
            ("Select the resource ensuring a pod runs on EVERY node in the cluster: 'We deployed the monitoring agent as a ___ across all worker nodes.'", ["DaemonSet", "StatefulSet", "Job", "ReplicaSet"], "DaemonSet", "Un DaemonSet garantit l'exécution d'une copie du pod sur chaque nœud."),
            ("Complete for stateful applications like databases: 'A Kubernetes ___ provides stable network identifiers and persistent storage bindings.'", ["StatefulSet", "Deployment", "DaemonSet", "Ingress"], "StatefulSet", "Un StatefulSet gère l'identité réseau stable et le stockage persistant."),
            ("Choose the probe checking if a container is ready to accept user traffic: 'The ___ probe removes unready pods from the Service load balancer endpoint list.'", ["readiness", "liveness", "startup", "reboot"], "readiness", "La sonde de readiness (readiness probe) contrôle l'aptitude à recevoir du trafic."),
            ("Select the probe restarting failing or deadlocked containers: 'If the ___ probe fails three consecutive times, kubelet restarts the container.'", ["liveness", "readiness", "startup", "ingress"], "liveness", "La sonde de liveness (liveness probe) redémarre les conteneurs défaillants."),
            ("Complete the resource limit definition: 'To prevent noisy-neighbor issues, we configure CPU and memory ___ on every container.'", ["requests and limits", "colors", "strings", "passwords"], "requests and limits", "Requests et Limits de ressources CPU/RAM."),
            ("Choose the component managing external HTTP/HTTPS routing into the cluster: 'An Ingress ___ translates Ingress rules into routing configurations.'", ["Controller (e.g. Nginx, Traefik)", "Master", "Kubelet", "Scheduler"], "Controller (e.g. Nginx, Traefik)", "Ingress Controller gère le routage d'entrée HTTP/HTTPS."),
            ("Complete: 'PodDisruptionBudgets (PDB) ensure that a minimum number of pods remain ___ during voluntary node maintenance.'", ["available", "deleted", "rebooted", "stopped"], "available", "PDB garantit la disponibilité minimale lors des maintenances de nœuds."),
            ("Select the multi-stage Docker build advantage: 'Multi-stage Docker builds produce ___ container images by excluding build tools from the runtime image.'", ["minimal / lightweight", "bloated", "heavy", "broken"], "minimal / lightweight", "Images minimales et légères sans dépendances de compilation."),
            ("Complete: 'A Kubernetes ___ groups a set of pods and provides a stable virtual IP address.'", ["Service", "Secret", "Volume", "Namespace"], "Service", "Un Service fournit une IP virtuelle stable devant un ensemble de pods."),
            ("Choose the tool used for declarative package management in Kubernetes: 'We package microservice manifests into parameterized ___ charts.'", ["Helm", "Docker", "Linux", "Git"], "Helm", "Helm charts (gestionnaire de packages Kubernetes)."),
            ("Complete: 'The Kubernetes ___ assigns newly created pods to optimal worker nodes based on resource capacity.'", ["Scheduler", "Kubelet", "Proxy", "Etcd"], "Scheduler", "Kube-Scheduler assigne les pods aux nœuds.")
        ],
        "quiz": [
            ("What is the difference between a Liveness Probe and a Readiness Probe in Kubernetes?", ["Liveness restarts failing containers; Readiness stops routing traffic to unready containers", "Liveness is for memory; Readiness is for CPU", "They are identical in functionality", "Liveness deletes the cluster; Readiness creates pods"], "Liveness restarts failing containers; Readiness stops routing traffic to unready containers", "Liveness = redémarrage en cas de crash ; Readiness = isolation du trafic."),
            ("What does a DaemonSet guarantee in a Kubernetes cluster?", ["That exactly one copy of a pod runs on each selected worker node in the cluster", "That pods run only on the master node", "That pods are deleted every midnight", "That containers have no memory limits"], "That exactly one copy of a pod runs on each selected worker node in the cluster", "Exécution d'un pod sur chaque nœud du cluster."),
            ("Complete: 'Persistent data in Kubernetes is attached via Persistent Volume ___ (PVC).'", ["Claims", "Certificates", "Controllers", "Clusters"], "Claims", "Persistent Volume Claim (PVC)."),
            ("What is the primary benefit of multi-stage Docker builds?", ["Drastically smaller container images with reduced attack surface", "Faster internet connections", "Free cloud credits", "Automatic database indexing"], "Drastically smaller container images with reduced attack surface", "Images réduites et surface d'attaque minimale.")
        ],
        "practice": [
            ("Configure Kubernetes health probes in a deployment specification:", ["Health Probe Spec: Configure `livenessProbe` on `/healthz` (interval: 10s) and `readinessProbe` on `/ready` (initialDelay: 5s).", "Health Probe Spec: Check if server is running sometimes.", "Health Probe Spec: Hope pods don't crash.", "Health Probe Spec: No probes needed."], "Health Probe Spec: Configure `livenessProbe` on `/healthz` (interval: 10s) and `readinessProbe` on `/ready` (initialDelay: 5s).", "Configuration formelle des sondes de santé."),
            ("Explain the role of a PodDisruptionBudget during node draining:", ["A PodDisruptionBudget with `minAvailable: 2` prevents `kubectl drain` from terminating pods if fewer than two replicas would remain healthy.", "PDB means we delete pods during node drain.", "PDB stops all cluster upgrades permanently.", "PDB has no impact on node maintenance."], "A PodDisruptionBudget with `minAvailable: 2` prevents `kubectl drain` from terminating pods if fewer than two replicas would remain healthy.", "Protection de la haute disponibilité lors des maintenances."),
            ("Describe a multi-stage Dockerfile architecture for a Go application:", ["Stage 1 uses `golang:1.22-alpine` to compile the binary; Stage 2 copies the compiled artifact into a minimal `scratch` image.", "We copy all source code and compilers into the production container.", "Single stage Dockerfiles are best for production.", "Dockerfiles should include all build tools."], "Stage 1 uses `golang:1.22-alpine` to compile the binary; Stage 2 copies the compiled artifact into a minimal `scratch` image.", "Pattern multi-stage Docker optimisé."),
            ("Define a Kubernetes Service selector matching worker pods:", ["The Service targets backend pods using `selector: app: payment, tier: api` on TCP port 8080.", "The Service connects to all random pods in the cluster.", "The Service requires hardcoded IP addresses.", "The Service has no selector."], "The Service targets backend pods using `selector: app: payment, tier: api` on TCP port 8080.", "Définition de sélecteur de Service Kubernetes.")
        ]
    },

    154: {
        "title": "Observability, Metrics and Telemetry",
        "questions": [
            ("Choose the Four Golden Signals of observability defined by Google SRE:", ["Latency, Traffic, Errors, and Saturation", "CPU, RAM, Disk, and Network", "Logs, Traces, Metrics, and Code", "Speed, Uptime, Money, and Tests"], "Latency, Traffic, Errors, and Saturation", "Les 4 signaux d'or SRE : Latence, Trafic, Erreurs et Saturation."),
            ("Select the metric type measuring a rate of events: 'Prometheus uses a ___ metric to count total incoming HTTP requests monotonically.'", ["Counter", "Gauge", "Histogram", "Summary"], "Counter", "Un Counter s'incrémente de manière monotone pour compter des événements."),
            ("Complete for fluctuating values: 'A Prometheus ___ measures instantaneous values that can go up and down, such as memory usage.'", ["Gauge", "Counter", "Histogram", "String"], "Gauge", "Un Gauge mesure une valeur instantanée pouvant augmenter ou diminuer."),
            ("Choose the observability pillar tracking request flow across microservices: 'Distributed ___ assigns a unique Trace ID to follow requests through distributed hops.'", ["tracing (e.g. OpenTelemetry, Jaeger)", "logging", "profiling", "alerting"], "tracing (e.g. OpenTelemetry, Jaeger)", "Traçabilité distribuée avec Trace ID."),
            ("Select the structured format recommended for machine-parseable log aggregation:", ["JSON", "Plain unstructured text", "Binary dump", "Word document"], "JSON", "Format JSON structuré pour l'indexation dans Elasticsearch/Loki."),
            ("Complete: 'To measure response time distribution and percentiles, use a Prometheus ___.'", ["Histogram", "Counter", "String", "Boolean"], "Histogram", "Un Histogram calcule les distributions et percentiles (p50, p95, p99)."),
            ("Choose the term for metric cardinality explosion: 'Adding high-cardinality user IDs as Prometheus labels causes severe memory ___.'", ["exhaustion / explosion", "reduction", "optimization", "compression"], "exhaustion / explosion", "Explosion de cardinalité due à des labels à valeurs uniques."),
            ("Complete: 'Alert ___ occurs when engineers receive too many non-actionable notifications, leading to missed critical alerts.'", ["fatigue", "optimization", "speed", "boost"], "fatigue", "Alert fatigue (fatigue d'alerte)."),
            ("Select the OpenTelemetry specification standard: 'OpenTelemetry provides vendor-neutral APIs and SDKs for generating, collecting, and exporting ___.'", ["telemetry data (metrics, logs, traces)", "source code", "passwords", "HTML files"], "telemetry data (metrics, logs, traces)", "Standard OpenTelemetry pour métriques, logs et traces."),
            ("Complete: 'A span in distributed tracing represents a single unit of ___ within a service boundary.'", ["work / execution", "storage", "hardware", "bandwidth"], "work / execution", "Un span représente une unité de travail délimitée."),
            ("Choose the query language used in Prometheus monitoring: 'We write alerting rules using ___ queries.'", ["PromQL", "SQL", "HTML", "Bash"], "PromQL", "PromQL = Prometheus Query Language.")
        ],
        "quiz": [
            ("What are the Three Pillars of Observability?", ["Metrics, Logs, and Traces", "CPU, RAM, and Disk", "HTML, CSS, and JS", "Firewall, Router, and Switch"], "Metrics, Logs, and Traces", "Métriques, Logs et Traces (les 3 piliers)."),
            ("What is the difference between a Counter and a Gauge in Prometheus?", ["A Counter only increases (or resets on restart); a Gauge can increase and decrease arbitrarily", "A Counter is for RAM; a Gauge is for CPU", "They are identical in functionality", "A Gauge only counts errors"], "A Counter only increases (or resets on restart); a Gauge can increase and decrease arbitrarily", "Counter = monotone croissant ; Gauge = valeur instantanée variable."),
            ("What causes 'high cardinality' in time-series metrics databases?", ["Using labels with millions of unique values (e.g. user_id, email, IP address) on Prometheus metrics", "Having too many servers", "Writing short queries", "Upgrading the database"], "Using labels with millions of unique values (e.g. user_id, email, IP address) on Prometheus metrics", "Labels à valeurs uniques multiples générant des millions de séries temporelles."),
            ("Complete: 'In distributed tracing, a ___ contains multiple interconnected spans.'", ["trace", "log", "metric", "counter"], "trace", "Une trace regroupe plusieurs spans.")
        ],
        "practice": [
            ("Define the four golden signals monitoring strategy for an API service:", ["Monitoring Strategy: Track p99 Latency (ms), Traffic (req/sec), Error Rate (5xx percentage), and CPU/RAM Saturation (%) via Prometheus and Grafana dashboards.", "Monitoring Strategy: Look at server logs manually once a day.", "Monitoring Strategy: Check if website opens in browser.", "Monitoring Strategy: Ask users on Twitter if API is fast."], "Monitoring Strategy: Track p99 Latency (ms), Traffic (req/sec), Error Rate (5xx percentage), and CPU/RAM Saturation (%) via Prometheus and Grafana dashboards.", "Stratégie de surveillance SRE fondée sur les 4 signaux d'or."),
            ("Formulate an actionable PromQL alert rule without alert fatigue:", ["Alert Rule: Trigger PagerDuty if `rate(http_requests_total{status=~'5..'}[5m]) / rate(http_requests_total[5m]) > 0.02` for more than 3 consecutive minutes.", "Alert Rule: Alert on every single 500 error immediately.", "Alert Rule: Send an email whenever CPU is 50%.", "Alert Rule: Alert all engineers every 5 minutes."], "Alert Rule: Trigger PagerDuty if `rate(http_requests_total{status=~'5..'}[5m]) / rate(http_requests_total[5m]) > 0.02` for more than 3 consecutive minutes.", "Alerte PromQL actionnable avec seuil temporel et ratio."),
            ("Explain the role of distributed tracing in diagnosing slow microservice calls:", ["Distributed tracing correlates requests with a shared Trace ID across gRPC and HTTP hops, pinpointing the exact microservice causing downstream latency spikes.", "Distributed tracing replaces all unit testing in Go.", "Tracing is only used for debugging CSS.", "Distributed tracing deletes old logs automatically."], "Distributed tracing correlates requests with a shared Trace ID across gRPC and HTTP hops, pinpointing the exact microservice causing downstream latency spikes.", "Diagnostic fin de la latence inter-microservices via Trace ID."),
            ("Advise against high-cardinality labels on Prometheus metrics in a code review:", ["Avoid adding `user_id` as a Prometheus label because millions of unique values will trigger metric cardinality explosion and crash the Prometheus server.", "Adding user_id to labels is a great idea.", "Prometheus can handle infinite unique labels with zero RAM.", "Always put email addresses in metrics labels."], "Avoid adding `user_id` as a Prometheus label because millions of unique values will trigger metric cardinality explosion and crash the Prometheus server.", "Mise en garde DevSecOps contre l'explosion de cardinalité.")
        ]
    },

    155: {
        "title": "High Availability, Load Balancing and Auto-Scaling",
        "questions": [
            ("Choose the auto-scaling mechanism adjusting Kubernetes pods: 'The Horizontal Pod Autoscaler (___) scales pod replicas based on CPU utilization and custom metrics.'", ["HPA", "VPA", "DNS", "WAF"], "HPA", "Horizontal Pod Autoscaler (HPA)."),
            ("Select the load balancing algorithm distributing traffic sequentially: 'The ___ algorithm routes each incoming request to the next backend server in cyclical order.'", ["Round Robin", "Least Connections", "IP Hash", "Random"], "Round Robin", "Round Robin distribue les requêtes de manière séquentielle et cyclique."),
            ("Complete for stateful sessions: 'Session ___ (sticky sessions) ensures that requests from the same client are routed to the same backend instance.'", ["affinity", "rejection", "destruction", "routing"], "affinity", "Session affinity / sticky sessions."),
            ("Choose the load balancing algorithm routing to the least busy node: '___ directs traffic to the server with the fewest active concurrent requests.'", ["Least Connections", "Round Robin", "Random", "Broadcast"], "Least Connections", "Least Connections dirige vers l'instance la moins sollicitée."),
            ("Select the architecture eliminating single points of failure: 'Deploying across multiple Availability Zones (Multi-AZ) provides automated ___ in case of datacenter loss.'", ["failover / redundancy", "latency", "billing", "reboots"], "failover / redundancy", "Redondance multi-AZ et bascule automatique."),
            ("Complete: 'The circuit breaker pattern trips to ___ state when upstream error rates exceed configured thresholds.'", ["Open", "Closed", "Half-Open", "Deleted"], "Open", "L'état 'Open' du circuit breaker bloque les requêtes pour protéger le service."),
            ("Choose the term for scaling server capacity vertically: 'Scaling ___ increases CPU and RAM on existing nodes rather than adding more instances.'", ["up", "out", "down", "in"], "up", "Scale up (mise à l'échelle verticale)."),
            ("Complete: 'A health check mechanism automatically removes ___ backend nodes from the load balancer target group.'", ["unhealthy / degraded", "healthy", "new", "fast"], "unhealthy / degraded", "Retrait automatique des nœuds dégradés."),
            ("Select the DNS load balancing technique: '___ DNS returns multiple IP addresses in rotating order for basic client-side distribution.'", ["Round-robin", "Anycast", "Unicast", "Multicast"], "Round-robin", "Round-robin DNS."),
            ("Complete: 'Network routing using ___ allows multiple edge servers worldwide to share a single public IP address.'", ["Anycast", "NAT", "BGP only", "VPC"], "Anycast", "Routage Anycast."),
            ("Choose the pattern handling sudden burst traffic: 'We implemented a rate limiter and request queue to ___ traffic spikes and prevent saturation.'", ["smooth / buffer", "increase", "double", "ignore"], "smooth / buffer", "Lissage et mise en mémoire tampon des pics de trafic."),
            ("Complete: 'High availability systems target an architectural design with zero Single Points of ___ (SPOF).'", ["Failure", "Traffic", "Success", "Latency"], "Failure", "Single Point of Failure (SPOF).")
        ],
        "quiz": [
            ("What does 'SPOF' stand for in high-availability systems architecture?", ["Single Point of Failure", "System Power Outage Frequency", "Standard Packet Over Flow", "Secure Protocol Option Flag"], "Single Point of Failure", "Point unique de défaillance (SPOF)."),
            ("What is the difference between scaling up (vertical) and scaling out (horizontal)?", ["Scaling up adds CPU/RAM to an existing server; Scaling out adds more server instances to a cluster", "Scaling up is for databases; Scaling out is for cables", "They are identical in architecture", "Scaling up is free; Scaling out is forbidden"], "Scaling up adds CPU/RAM to an existing server; Scaling out adds more server instances to a cluster", "Scale up = puissance machine ; Scale out = ajout d'instances."),
            ("What are the three states of the Circuit Breaker pattern?", ["Closed (normal), Open (tripped/blocking), and Half-Open (testing recovery)", "On, Off, Broken", "Fast, Slow, Dead", "Green, Yellow, Red"], "Closed (normal), Open (tripped/blocking), and Half-Open (testing recovery)", "États Closed, Open et Half-Open."),
            ("Complete: 'Kubernetes HPA scales pod replicas based on metrics like CPU ___.'", ["utilization / percentage", "color", "name length", "creation date"], "utilization / percentage", "Taux d'utilisation CPU/RAM.")
        ],
        "practice": [
            ("Define the auto-scaling policy for an e-commerce microservice:", ["Auto-Scaling Policy: Configure Kubernetes HPA with `minReplicas: 3`, `maxReplicas: 30`, scaling up when average CPU utilization exceeds 70%.", "Auto-Scaling Policy: Add servers when users complain.", "Auto-Scaling Policy: Keep 1 pod forever.", "Auto-Scaling Policy: Scale randomly."], "Auto-Scaling Policy: Configure Kubernetes HPA with `minReplicas: 3`, `maxReplicas: 30`, scaling up when average CPU utilization exceeds 70%.", "Règle HPA formelle et chiffrée."),
            ("Document a Multi-AZ disaster recovery architecture eliminating SPOFs:", ["High Availability Architecture: The database cluster is deployed across three AWS Availability Zones with synchronous standby replication and zero SPOFs.", "HA Architecture: We run all servers on a single physical machine in one room.", "HA Architecture: One server is enough for high availability.", "HA Architecture: Multi-AZ is unnecessary."], "High Availability Architecture: The database cluster is deployed across three AWS Availability Zones with synchronous standby replication and zero SPOFs.", "Architecture haute disponibilité multi-AZ sans SPOF."),
            ("Explain the role of the Circuit Breaker pattern in microservices:", ["The circuit breaker prevents cascading cluster failures by temporarily returning cached fallback responses when the external payment API becomes unresponsive.", "Circuit breakers terminate all microservices permanently.", "Circuit breakers are physical hardware fuses only.", "Circuit breakers increase database latency."], "The circuit breaker prevents cascading cluster failures by temporarily returning cached fallback responses when the external payment API becomes unresponsive.", "Protection contre les pannes en cascade."),
            ("Select the appropriate load balancing algorithm for long-lived WebSocket sessions:", ["Use the Least Connections algorithm with IP hash or cookie-based session affinity to ensure balanced WebSocket connection distribution.", "Use random load balancing without health checks.", "Route all traffic to a single node.", "Disable load balancing for WebSockets."], "Use the Least Connections algorithm with IP hash or cookie-based session affinity to ensure balanced WebSocket connection distribution.", "Algorithme adapté aux connexions persistantes.")
        ]
    },

    156: {
        "title": "Cloud Storage Classes and Lifecycle Rules",
        "questions": [
            ("Choose the cloud storage tier for infrequently accessed archive data: 'Amazon S3 ___ provides ultra-low cost archival storage with retrieval times of several hours.'", ["Glacier Flexible Retrieval / Deep Archive", "Standard", "Express One Zone", "SSD"], "Glacier Flexible Retrieval / Deep Archive", "S3 Glacier / Deep Archive pour l'archivage froid."),
            ("Select the storage tier for active, frequently accessed objects: 'Use Amazon S3 ___ for high-throughput, low-latency daily application assets.'", ["Standard", "Glacier", "Deep Archive", "Coldline"], "Standard", "S3 Standard pour les données chaudes actives."),
            ("Complete the lifecycle policy definition: 'Lifecycle rules automatically ___ objects from S3 Standard to S3 Infrequent Access after 30 days.'", ["transition / migrate", "delete immediately", "encrypt", "corrupt"], "transition / migrate", "Transition automatique de classe de stockage."),
            ("Choose the data protection feature preserving previous object states: 'Enabling S3 ___ protects against accidental deletions and overwrites by preserving historical versions.'", ["Versioning", "Logging", "Replication", "Locking"], "Versioning", "S3 Versioning (gestion des versions d'objets)."),
            ("Select the security feature enforcing non-erasable compliance storage: 'S3 Object Lock enforces a ___ model (Write Once, Read Many) for financial compliance.'", ["WORM", "CRUD", "REST", "FIFO"], "WORM", "WORM = Write Once, Read Many (verrouillage d'objets immuables)."),
            ("Complete: 'Lifecycle expiration rules automatically ___ temporary upload artifacts after seven days.'", ["delete / expire", "replicate", "encrypt", "rename"], "delete / expire", "Expiration et suppression automatique des fichiers temporaires."),
            ("Choose the storage tier with automated intelligent cost tiering: 'S3 ___ automatically moves objects between access tiers based on changing access patterns.'", ["Intelligent-Tiering", "Standard", "Glacier", "One Zone"], "Intelligent-Tiering", "S3 Intelligent-Tiering optimise les coûts automatiquement."),
            ("Complete: 'Cross-Region Replication (CRR) replicates S3 objects ___ to a secondary AWS region for disaster recovery.'", ["asynchronously", "manually", "synchronously with zero delay", "never"], "asynchronously", "Réplication asynchrone inter-régions (CRR)."),
            ("Select the security requirement for cloud storage: 'All S3 buckets must enforce server-side ___ (SSE-KMS) and block public access by default.'", ["encryption", "deletion", "sharing", "indexing"], "encryption", "Chiffrement côté serveur SSE-KMS et blocage des accès publics."),
            ("Complete: 'To optimize download speeds for global users, attach an Amazon CloudFront ___ distribution in front of the S3 bucket.'", ["CDN", "VPC", "EC2", "NAT"], "CDN", "Distribution CDN CloudFront."),
            ("Choose the protocol for bulk data transfer: 'Multipart upload splits large files into parallel chunks, enabling faster and more ___ uploads.'", ["resilient", "expensive", "insecure", "fragile"], "resilient", "Multipart upload pour les fichiers volumineux.")
        ],
        "quiz": [
            ("What does 'WORM' storage mean in regulatory data compliance?", ["Write Once, Read Many (data cannot be deleted or modified during the retention period)", "Write Often, Read Most", "Web Oriented Resource Mapping", "Wide Optical Read Media"], "Write Once, Read Many (data cannot be deleted or modified during the retention period)", "Stockage immuable non modifiable ni supprimable."),
            ("What is the primary function of S3 Lifecycle Rules?", ["Automating the transition of objects to colder storage tiers and expiring old data to optimize costs", "Running Python scripts inside storage", "Renaming files daily", "Creating user accounts"], "Automating the transition of objects to colder storage tiers and expiring old data to optimize costs", "Automatisation de la transition et suppression pour optimiser les coûts."),
            ("Complete: 'S3 Glacier Deep Archive is designed for long-term data retention accessed ___ per year.'", ["once or twice", "every minute", "thousands of times a day", "continuously"], "once or twice", "Archivage ultra-froid consulté très rarement."),
            ("Why is S3 Object Versioning recommended before enabling lifecycle rules?", ["It prevents permanent data loss from accidental user deletion or flawed lifecycle filters", "It makes files smaller", "It reduces network bandwidth to zero", "It is legally mandatory for all websites"], "It prevents permanent data loss from accidental user deletion or flawed lifecycle filters", "Protection contre les suppressions accidentelles.")
        ],
        "practice": [
            ("Define an S3 lifecycle policy in a cloud architecture document:", ["Lifecycle Policy: Transition objects from S3 Standard to S3 Standard-IA after 30 days, move to S3 Glacier after 90 days, and permanently expire after 365 days.", "Lifecycle Policy: Delete everything after 1 day.", "Lifecycle Policy: Keep everything in S3 Standard forever.", "Lifecycle Policy: Files will move randomly."], "Lifecycle Policy: Transition objects from S3 Standard to S3 Standard-IA after 30 days, move to S3 Glacier after 90 days, and permanently expire after 365 days.", "Politique de cycle de vie hiérarchisée et optimisée."),
            ("Document regulatory audit compliance using S3 Object Lock:", ["To satisfy SEC Rule 17a-4 compliance, the `finance-audit-logs` bucket is configured with S3 Object Lock in Compliance mode with a 7-year retention period.", "Audit logs are saved in a normal bucket without protection.", "We tell employees not to delete finance files.", "Finance logs are deleted after each audit."], "To satisfy SEC Rule 17a-4 compliance, the `finance-audit-logs` bucket is configured with S3 Object Lock in Compliance mode with a 7-year retention period.", "Configuration de conformité immuable (WORM)."),
            ("Specify Cross-Region Replication requirements for disaster recovery:", ["Cross-Region Replication (CRR): All objects written to `app-backups-eu-west-1` are asynchronously replicated to `app-backups-us-east-1` within 15 minutes.", "Replication: We manually copy files once a month.", "Replication: Backups stay in one single region.", "Replication: We don't need cross-region backups."], "Cross-Region Replication (CRR): All objects written to `app-backups-eu-west-1` are asynchronously replicated to `app-backups-us-east-1` within 15 minutes.", "Réplication CRR documentée avec RPO."),
            ("Enforce default encryption and public access block on cloud buckets:", ["Security Standard: All cloud storage buckets must enable AWS KMS customer-managed encryption (SSE-KMS) and enforce S3 Block Public Access.", "Security Standard: S3 buckets can be public for easy sharing.", "Security Standard: Encryption is optional.", "Security Standard: No encryption keys needed."], "Security Standard: All cloud storage buckets must enable AWS KMS customer-managed encryption (SSE-KMS) and enforce S3 Block Public Access.", "Standard de sécurité du stockage cloud.")
        ]
    },

    157: {
        "title": "VPC Peering, Subnetting and Cloud Networking",
        "questions": [
            ("Choose the networking component enabling private communication between two VPCs: 'VPC ___ connects two Virtual Private Clouds directly using private IP routing.'", ["Peering", "Internet Gateway", "NAT Instance", "Bastion"], "Peering", "VPC Peering connecte deux VPC via des adresses IP privées."),
            ("Select the CIDR notation representing a subnet with 256 IP addresses: 'A /___ network mask provides 256 total IP addresses (251 usable in AWS).'/", ["24", "16", "28", "32"], "24", "Un masque /24 fournit 256 adresses IP (2^(32-24) = 256)."),
            ("Complete for outbound internet access from private subnets: 'Instances in a private subnet route outbound internet traffic through a ___ Gateway.'", ["NAT", "Internet", "Transit", "Direct Connect"], "NAT", "NAT Gateway permet l'accès sortant sécurisé depuis un subnet privé."),
            ("Choose the scalable hub-and-spoke networking component: 'AWS ___ Gateway simplifies connecting hundreds of VPCs and on-premises networks to a central hub.'", ["Transit", "Internet", "NAT", "Peering"], "Transit", "AWS Transit Gateway (architecture hub-and-spoke centralisée)."),
            ("Select the security component filtering traffic at the subnet boundary: 'Network Access Control Lists (NACLs) operate at the subnet layer and are ___.'", ["stateless", "stateful", "encrypted", "hardware"], "stateless", "Les NACLs sont 'stateless' (sans état, règles aller et retour requises)."),
            ("Complete for instance-level traffic filtering: 'Security Groups operate at the elastic network interface (ENI) level and are ___.'", ["stateful", "stateless", "unencrypted", "broadcast"], "stateful", "Les Security Groups sont 'stateful' (avec état, réponse automatique autorisée)."),
            ("Choose the non-overlapping IP allocation rule: 'VPC Peering connection will fail if the two VPCs have ___ CIDR blocks.'", ["overlapping", "isolated", "different", "unique"], "overlapping", "Le peering VPC échoue si les plages IP se chevauchent (overlapping CIDR)."),
            ("Complete: 'A ___ table contains a set of rules (routes) determining where network traffic is directed.'", ["route", "database", "hash", "cache"], "route", "Route table (table de routage réseau)."),
            ("Select the dedicated private connection from on-premise datacenter to cloud: 'AWS ___ Connect establishes a dedicated physical fiber connection bypassing the public internet.'", ["Direct", "VPC", "Transit", "NAT"], "Direct", "AWS Direct Connect (liaison physique dédiée)."),
            ("Complete: 'To route traffic privately to AWS services like S3 without an internet gateway, provision a VPC ___.'", ["Endpoint (PrivateLink / Gateway)", "Public IP", "Bastion host", "Firewall"], "Endpoint (PrivateLink / Gateway)", "VPC Endpoints / PrivateLink pour l'accès privé aux services AWS."),
            ("Choose the subnet classification: 'A subnet is considered ___ if its route table has a direct route to an Internet Gateway (0.0.0.0/0 -> igw).' ", ["public", "private", "isolated", "offline"], "public", "Sous-réseau public (route directe vers l'IGW)."),
            ("Complete: 'Border Gateway Protocol (___) dynamically exchanges routing information over Direct Connect and VPN connections.'", ["BGP", "DNS", "DHCP", "HTTP"], "BGP", "BGP (Border Gateway Protocol).")
        ],
        "quiz": [
            ("What is the fundamental difference between Security Groups and Network ACLs (NACLs)?", ["Security Groups are stateful and applied at the instance/ENI level; NACLs are stateless and applied at the subnet boundary", "Security Groups are for Linux; NACLs are for Windows", "They are identical in functionality", "Security Groups filter incoming traffic only; NACLs filter nothing"], "Security Groups are stateful and applied at the instance/ENI level; NACLs are stateless and applied at the subnet boundary", "Security Groups = stateful au niveau instance ; NACLs = stateless au niveau sous-réseau."),
            ("Why is overlapping CIDR block allocation prohibited in VPC Peering?", ["Because IP routers cannot determine which VPC an IP address belongs to if both VPCs share the same address range (e.g. 10.0.0.0/16)", "Because AWS runs out of cables", "To increase cloud billing costs", "Because IPv4 cannot route private IPs"], "Because IP routers cannot determine which VPC an IP address belongs to if both VPCs share the same address range (e.g. 10.0.0.0/16)", "Impossibilité de routage en cas de collision d'adresses IP."),
            ("Complete: 'AWS Transit Gateway uses a hub-and-___ network topology.'", ["spoke", "wheel", "circle", "mesh"], "spoke", "Hub-and-spoke topology."),
            ("What component is required for a private subnet instance to download software updates from the internet?", ["NAT Gateway (or NAT Instance) in a public subnet", "Internet Gateway attached directly to the private subnet", "Public IP on the private instance", "VPC Peering with Google"], "NAT Gateway (or NAT Instance) in a public subnet", "NAT Gateway placé dans un sous-réseau public.")
        ],
        "practice": [
            ("Document a non-overlapping multi-VPC network architecture:", ["VPC Network Plan: Production VPC (`10.100.0.0/16`), Staging VPC (`10.101.0.0/16`), and Shared Services VPC (`10.102.0.0/16`) interconnected via AWS Transit Gateway.", "Network Plan: Give all VPCs the IP range 10.0.0.0/16.", "Network Plan: We will figure out IPs later.", "Network Plan: Public IPs for all database servers."], "VPC Network Plan: Production VPC (`10.100.0.0/16`), Staging VPC (`10.101.0.0/16`), and Shared Services VPC (`10.102.0.0/16`) interconnected via AWS Transit Gateway.", "Plan d'adressage IP sans chevauchement avec Transit Gateway."),
            ("Configure private egress routing in a route table definition:", ["Private Subnet Route Table: Route `10.100.0.0/16` locally, and route `0.0.0.0/0` to `nat-0123456789abcdef0` in public-subnet-1a.", "Private Route Table: Route all traffic to internet gateway directly.", "Private Route Table: Delete all routes.", "Private Route Table: No default gateway needed."], "Private Subnet Route Table: Route `10.100.0.0/16` locally, and route `0.0.0.0/0` to `nat-0123456789abcdef0` in public-subnet-1a.", "Configuration de table de routage privée vers NAT Gateway."),
            ("Explain the security advantages of VPC Endpoints / PrivateLink in an architecture review:", ["VPC Endpoints allow our EC2 instances to access Amazon S3 and DynamoDB entirely over the AWS private backbone, eliminating internet egress exposure.", "VPC Endpoints make traffic faster by using public internet.", "VPC Endpoints disable encryption.", "VPC Endpoints require opening port 80 to the world."], "VPC Endpoints allow our EC2 instances to access Amazon S3 and DynamoDB entirely over the AWS private backbone, eliminating internet egress exposure.", "Accès privé aux services managés sans exposition internet."),
            ("Specify ingress Security Group rules for an internal database tier:", ["Security Group `sg-postgres`: Ingress allows TCP port 5432 strictly from `sg-backend-api`; all external public access is blocked.", "Security Group: Allow port 5432 from 0.0.0.0/0.", "Security Group: Open all ports for easy debugging.", "Security Group: No inbound rules needed."], "Security Group `sg-postgres`: Ingress allows TCP port 5432 strictly from `sg-backend-api`; all external public access is blocked.", "Règle de groupe de sécurité au principe du moindre privilège.")
        ]
    },

    158: {
        "title": "Chaos Engineering and System Resilience",
        "questions": [
            ("Choose the definition of Chaos Engineering: 'Chaos Engineering is the discipline of experimenting on a system to build confidence in its capability to withstand ___ conditions in production.'", ["turbulent / unexpected", "peaceful", "offline", "untested"], "turbulent / unexpected", "Discipline d'expérimentation pour éprouver la résilience sous conditions turbulentes."),
            ("Select the chaos experiment tool: 'We inject network latency and pod termination experiments using ___.'", ["Chaos Mesh / Chaos Engineering tools", "Microsoft Word", "Photoshop", "Git commit"], "Chaos Mesh / Chaos Engineering tools", "Outils d'ingénierie du chaos (Chaos Mesh, Gremlin, Chaos Toolkit)."),
            ("Complete the hypothesis formulation: 'Hypothesis: Terminating two random payment pods during peak traffic will not cause API error rates to exceed ___.'", ["0.01%", "100%", "50%", "10%"], "0.01%", "Hypothèse d'état stable (steady state hypothesis)."),
            ("Choose the concept limiting experiment impact: 'Always define a strict ___ radius to ensure chaos experiments do not cause uncontained customer outages.'", ["blast", "color", "speed", "height"], "blast", "Blast radius (périmètre et rayon de confinement de l'expérience)."),
            ("Select the baseline measurement before injecting faults: 'Verify that the system is in a ___ state before initiating chaos injection.'", ["steady / nominal", "crashed", "rebooting", "broken"], "steady / nominal", "Validation préalable de l'état stable (steady state)."),
            ("Complete: 'The emergency ___ switch immediately halts the chaos experiment and restores nominal routing if SLOs are breached.'", ["kill / abort", "on", "start", "speed"], "kill / abort", "Bouton d'arrêt d'urgence (Kill switch)."),
            ("Choose the fault injection scenario simulating network degradation: 'We injected 250ms of artificial packet ___ to verify client retry backoff algorithms.'", ["latency / jitter", "destruction", "deletion", "speed"], "latency / jitter", "Injection artificielle de latence et gigue réseau."),
            ("Complete: 'Chaos experiments revealed that the database driver lacked connection ___ configuration, causing worker thread exhaustion.'", ["timeout", "color", "password", "cable"], "timeout", "Découverte de l'absence de timeout dans le driver."),
            ("Select the resilience pattern tested during chaos drills: 'We verified that our exponential ___ with jitter prevented thundering herd problems during database recovery.'", ["backoff", "speed", "growth", "burst"], "backoff", "Algorithme d'exponential backoff avec gigue (jitter)."),
            ("Complete: 'GameDay exercises simulate catastrophic cloud region ___ to train engineering on-call teams.'", ["failovers / outages", "parties", "holidays", "meetings"], "failovers / outages", "Exercices GameDay simulant des pannes d'infrastructure réelles."),
            ("Choose the resilience metric verified by chaos testing: 'The experiment proved that self-healing mechanisms restored full pod count within ___ seconds.'", ["twenty", "days", "months", "years"], "twenty", "Mesure du temps d'auto-guérison (self-healing).")
        ],
        "quiz": [
            ("What is a 'Steady State Hypothesis' in Chaos Engineering?", ["The measurable definition of normal, healthy system behavior that must be maintained during fault injection", "A statement that bugs are impossible", "The hypothesis that cloud providers never fail", "A mathematical theory of physics"], "The measurable definition of normal, healthy system behavior that must be maintained during fault injection", "Définition mesurable de l'état de fonctionnement nominal."),
            ("What is the purpose of an automated 'Kill Switch' in chaos experiments?", ["To immediately abort the experiment and roll back all injected faults if critical customer SLOs are violated", "To turn off the building power", "To delete the cluster permanently", "To format developer hard drives"], "To immediately abort the experiment and roll back all injected faults if critical customer SLOs are violated", "Arrêt immédiat de l'expérience en cas de dépassement des seuils critiques."),
            ("Complete: 'Exponential ___ with randomized jitter prevents thundering herd retry storms.'", ["backoff", "speed", "forward", "acceleration"], "backoff", "Exponential backoff."),
            ("What is a 'GameDay' in SRE culture?", ["A scheduled team exercise where engineers simulate catastrophic failures and practice emergency response protocols", "A day for playing video games in the office", "A sports tournament", "A day where no work is allowed"], "A scheduled team exercise where engineers simulate catastrophic failures and practice emergency response protocols", "Exercice de simulation grandeur nature de gestion de crise.")
        ],
        "practice": [
            ("Formulate a formal Chaos Engineering experiment proposal:", ["Experiment: Inject 30% packet loss between the frontend and auth microservices. Steady State Hypothesis: Error rates will remain under 0.05% due to retry backoff and circuit breaking.", "Experiment: Break the servers and see what happens.", "Experiment: Turn off AWS and hope for the best.", "Experiment: Random chaos in production."], "Experiment: Inject 30% packet loss between the frontend and auth microservices. Steady State Hypothesis: Error rates will remain under 0.05% due to retry backoff and circuit breaking.", "Protocole d'expérience de chaos formalisé et mesurable."),
            ("Document automated kill switch criteria for a GameDay exercise:", ["Kill Switch Trigger: If p99 checkout latency exceeds 500ms or HTTP 5xx error rate exceeds 0.5% for more than 30 seconds, immediately abort the Chaos Mesh experiment.", "Kill Switch: Stop the test if people start shouting.", "Kill Switch: No abort condition needed.", "Kill Switch: Let production burn."], "Kill Switch Trigger: If p99 checkout latency exceeds 500ms or HTTP 5xx error rate exceeds 0.5% for more than 30 seconds, immediately abort the Chaos Mesh experiment.", "Conditions d'arrêt d'urgence objectives et chiffrées."),
            ("Document findings and architectural remediations from a chaos drill:", ["Chaos Drill Finding: Pod termination revealed that the payment service lacked graceful shutdown handling; remediated by adding `preStop` lifecycle hooks.", "Finding: The app broke and we don't know why.", "Finding: Chaos is dangerous, never do it again.", "Finding: No issues found."], "Chaos Drill Finding: Pod termination revealed that the payment service lacked graceful shutdown handling; remediated by adding `preStop` lifecycle hooks.", "Bilan d'apprentissage et remédiation technique issue du chaos."),
            ("Explain the concept of blast radius containment to leadership:", ["We contain the blast radius of chaos experiments by running them against a synthetic 2% user canary cohort before ever scaling to broader production traffic.", "Blast radius means we explode things in the cloud.", "We don't limit blast radius because full failure is better.", "Blast radius cannot be controlled."], "We contain the blast radius of chaos experiments by running them against a synthetic 2% user canary cohort before ever scaling to broader production traffic.", "Explication claire de la maîtrise des risques pour la direction.")
        ]
    },

    159: {
        "title": "FinOps: Cloud Cost Optimization and Right-Sizing",
        "questions": [
            ("Choose the FinOps term for matching instance compute capacity to actual workload demands: '___ involves analyzing CPU/RAM metrics and downsizing over-provisioned virtual machines.'", ["Right-sizing", "Over-clocking", "Re-platforming", "Decommissioning"], "Right-sizing", "Right-sizing (dimensionnement optimal des ressources au plus juste besoin)."),
            ("Select the cloud pricing model offering deep discounts in exchange for 1- or 3-year commitments: 'AWS ___ Plans provide up to 72% savings compared to On-Demand pricing.'", ["Savings", "On-Demand", "Spot", "Free"], "Savings", "AWS Savings Plans / Reserved Instances (engagement 1 ou 3 ans)."),
            ("Complete for non-critical fault-tolerant workloads: '___ instances utilize spare cloud capacity at steep discounts (up to 90%), but can be reclaimed with 2 minutes notice.'", ["Spot", "Dedicated", "Reserved", "On-Demand"], "Spot", "Spot instances (instances excédentaires à bas coût préemptibles)."),
            ("Choose the term for allocating cloud spend back to engineering teams: 'Cost ___ assigns cloud infrastructure costs to specific product units using metadata tags.'", ["allocation / showback", "destruction", "reduction", "inflation"], "allocation / showback", "Cost allocation / Showback (ventilation des coûts par équipe/tag)."),
            ("Select the metric measuring the cloud cost per business transaction: 'FinOps teams track ___ economics, such as cost per active user or cost per payment transaction.'", ["unit", "macro", "inflationary", "market"], "unit", "Unit economics (coût unitaire par transaction métier)."),
            ("Complete: 'Automated cleanup scripts terminate ___ Elastic IP addresses and unattached EBS volumes to prevent waste.'", ["orphan / idle", "active", "encrypted", "reserved"], "orphan / idle", "Suppression des ressources orphelines (EBS non attachés, EIPs inutilisées)."),
            ("Choose the term for non-production scheduling: 'We implemented automated ___ to shut down staging and development environments outside business hours.'", ["scheduling / sleep schedules", "overclocking", "scaling out", "replication"], "scheduling / sleep schedules", "Extinction programmée des environnements de dev hors heures ouvrées."),
            ("Complete: 'Graviton (ARM64) processors provide a 20% to 40% superior ___ ratio compared to x86 instances.'", ["price-performance", "storage-speed", "weight-height", "network-ping"], "price-performance", "Ratio prix/performance supérieur des processeurs ARM (Graviton)."),
            ("Select the FinOps maturity phase: 'The FinOps framework progresses through three continuous phases: Inform, ___, and Operate.'", ["Optimize", "Destroy", "Cancel", "Ignore"], "Optimize", "Les 3 phases FinOps : Inform, Optimize, Operate."),
            ("Complete: 'Enforcing mandatory resource ___ ensures that every cloud asset has an `Owner`, `Environment`, and `CostCenter` identifier.'", ["tagging", "naming", "password", "certificate"], "tagging", "Politique de tagging obligatoire pour le suivi budgétaire."),
            ("Choose the tool visualizing cloud spend anomalies: 'We configured AWS Cost ___ to alert finance teams when daily spend spikes unexpectedly.'", ["Anomaly Detection", "Destroyer", "Reducer", "Halter"], "Anomaly Detection", "AWS Cost Anomaly Detection (détection des dérives budgétaires)."),
            ("Complete: 'By rightsizing our RDS database fleet, we achieved a $15,000 monthly ___ reduction without degrading p99 query latency.'", ["cost / spend", "traffic", "memory", "storage"], "cost / spend", "Réduction des coûts cloud sans perte de performance.")
        ],
        "quiz": [
            ("What are the Three Core Phases of the FinOps Lifecycle?", ["Inform, Optimize, and Operate", "Buy, Use, and Sell", "Plan, Code, and Test", "Create, Scale, and Delete"], "Inform, Optimize, and Operate", "Inform, Optimize, Operate (cycle de vie FinOps)."),
            ("What is 'Right-sizing' in cloud infrastructure management?", ["Analyzing resource utilization metrics and downsizing underutilized instances to eliminate over-provisioned spend", "Buying the biggest server available", "Renaming servers with correct names", "Deleting all production databases"], "Analyzing resource utilization metrics and downsizing underutilized instances to eliminate over-provisioned spend", "Ajustement de la taille des instances aux besoins réels."),
            ("Complete: 'AWS ___ instances offer up to 90% cost savings for stateless, fault-tolerant batch workloads.'", ["Spot", "On-Demand", "Dedicated", "Reserved"], "Spot", "Spot instances."),
            ("What is 'Unit Economics' in engineering FinOps?", ["Measuring cloud spend relative to business metrics (e.g. Cost per active user, Cost per checkout)", "The total bill from Amazon", "The price of one CPU core", "The salary of cloud engineers"], "Measuring cloud spend relative to business metrics (e.g. Cost per active user, Cost per checkout)", "Mesure du coût de l'infrastructure par unité de valeur métier.")
        ],
        "practice": [
            ("Formulate a cloud cost optimization proposal for executive leadership:", ["FinOps Proposal: By rightsizing over-provisioned Kubernetes clusters and purchasing 3-year Compute Savings Plans, we will reduce annual AWS spend by $180,000.", "Proposal: We want to spend less on AWS somehow.", "Proposal: Turn off all staging servers permanently.", "Proposal: Cloud is too expensive, let's complain."], "FinOps Proposal: By rightsizing over-provisioned Kubernetes clusters and purchasing 3-year Compute Savings Plans, we will reduce annual AWS spend by $180,000.", "Proposition d'optimisation financière chiffrée et argumentée."),
            ("Enforce a mandatory cloud resource tagging policy in an infrastructure standard:", ["Tagging Policy: All deployed cloud resources must include `Environment` (prod/stage), `Owner` (team-email), and `CostCenter` tags; untagged assets will be quarantined.", "Tagging Policy: Tag resources if you feel like it.", "Tagging Policy: Tags are optional for developers.", "Tagging Policy: Tags don't matter."], "Tagging Policy: All deployed cloud resources must include `Environment` (prod/stage), `Owner` (team-email), and `CostCenter` tags; untagged assets will be quarantined.", "Politique de balisage obligatoire pour l'imputabilité financière."),
            ("Document an automated schedule for non-production environment savings:", ["Cost Saving Action: Non-production development clusters are automatically shut down at 20:00 UTC on weekdays and remain off on weekends, cutting staging compute costs by 65%.", "Action: Developers should remember to turn off computers on Friday.", "Action: We leave staging running 24/7 forever.", "Action: No dev environments allowed."], "Cost Saving Action: Non-production development clusters are automatically shut down at 20:00 UTC on weekdays and remain off on weekends, cutting staging compute costs by 65%.", "Économie programmée sur les environnements hors production."),
            ("Analyze unit economics in a monthly engineering cost review:", ["Unit Cost Analysis: Infrastructure cost per 1,000 payment transactions decreased from $0.42 to $0.28 following our Graviton3 database migration.", "Unit Cost: We spent money on servers this month.", "Unit Cost: Transactions cost some dollars.", "Unit Cost: Cloud bill went up because we have users."], "Unit Cost Analysis: Infrastructure cost per 1,000 payment transactions decreased from $0.42 to $0.28 following our Graviton3 database migration.", "Démonstration du gain d'efficience par transaction unitaire.")
        ]
    },

    160: {
        "title": "Writing Infrastructure Capacity Reports",
        "questions": [
            ("Choose the term describing remaining resource buffer before saturation: 'Our primary database cluster currently maintains 35% CPU ___ under peak load.'", ["headroom", "tailroom", "sideway", "overrun"], "headroom", "Headroom (marge de sécurité / capacité disponible avant saturation)."),
            ("Select the forecasting methodology: 'Based on linear ___ of monthly telemetry data, storage capacity will reach 80% saturation by December.'", ["extrapolation / regression", "guessing", "wishing", "gambling"], "extrapolation / regression", "Extrapolation linéaire et régression statistique."),
            ("Complete the capacity planning objective: 'Capacity planning ensures that compute and storage resources are provisioned ahead of projected business ___.'", ["growth / demand", "failure", "stagnation", "holidays"], "growth / demand", "Anticipation de la croissance et de la demande métier."),
            ("Choose the term for database connection depletion: 'We forecasted connection pool ___ during the upcoming Black Friday promotional event.'", ["exhaustion / saturation", "inflation", "rotation", "optimization"], "exhaustion / saturation", "Saturation / épuisement du pool de connexions."),
            ("Select the executive recommendation phrase: 'We recommend ___ three additional read replicas before Q4 to maintain sub-50ms query latency.'", ["provisioning / commissioning", "deleting", "terminating", "ignoring"], "provisioning / commissioning", "Recommandation d'approvisionnement proactif."),
            ("Complete: 'The storage utilization trend indicates a monthly compound growth ___ of 8.5%.'", ["rate", "speed", "height", "distance"], "rate", "Growth rate (taux de croissance mensuel)."),
            ("Choose the phrase defining the resource exhaustion runway: 'At current ingestion velocity, the Kafka storage pool has a 90-day ___ before requiring disk expansion.'", ["runway", "delay", "pause", "stop"], "runway", "Runway (délai d'autonomie avant saturation)."),
            ("Complete: 'Network interface throughput reached 78% of maximum line ___ during the peak stress test.'", ["capacity / rate", "color", "price", "length"], "capacity / rate", "Capacité maximale de ligne réseau."),
            ("Select the risk statement in a capacity report:", ["Risk Assessment: Without vertical database scaling, the primary writer node will breach the 90% CPU threshold during peak holiday traffic.", "Risk: Things might be slow if users visit.", "Risk: Servers could be busy maybe.", "Risk: We hope capacity is enough."], "Risk Assessment: Without vertical database scaling, the primary writer node will breach the 90% CPU threshold during peak holiday traffic.", "Évaluation formelle et quantifiée du risque capacitaire."),
            ("Complete: 'The capacity plan includes a 25% safety ___ to absorb unforeseen traffic anomalies.'", ["margin / buffer", "loss", "waste", "reduction"], "margin / buffer", "Marge de sécurité (safety buffer / margin)."),
            ("Choose the closing executive summary sentence of a capacity report: 'In conclusion, the proposed infrastructure upgrades will support projected 3x user growth over the next twelve months with high reliability.'", ["In conclusion, the proposed infrastructure upgrades will support projected 3x user growth over the next twelve months with high reliability.", "We need more servers because traffic grows.", "That is our capacity report for the bosses.", "Capacity looks fine for now."], "In conclusion, the proposed infrastructure upgrades will support projected 3x user growth over the next twelve months with high reliability.", "Conclusion exécutive orientée croissance et fiabilité.")
        ],
        "quiz": [
            ("What does 'headroom' mean in infrastructure capacity planning?", ["The available compute, memory, or network buffer remaining before a system reaches saturation limits", "The height of the datacenter ceiling", "The memory taken by the operating system kernel", "The price of the cloud bill"], "The available compute, memory, or network buffer remaining before a system reaches saturation limits", "Marge de capacité disponible avant saturation."),
            ("What is 'capacity runway'?", ["The projected amount of time remaining before current resource consumption reaches critical capacity limits", "The runway where airplanes land with servers", "The speed of the network cable", "The time taken to run unit tests"], "The projected amount of time remaining before current resource consumption reaches critical capacity limits", "Délai temporel estimé avant épuisement des ressources."),
            ("Complete: 'Capacity forecasting utilizes historical trend ___ to predict future resource exhaustion.'", ["extrapolation / analysis", "guessing", "hoping", "praying"], "extrapolation / analysis", "Extrapolation des tendances historiques."),
            ("Why is capacity planning critical prior to major e-commerce promotional events?", ["To prevent catastrophic system outages caused by sudden resource saturation during peak user demand", "To buy unnecessary servers", "To make graphs look colorful", "To slow down the release cycle"], "To prevent catastrophic system outages caused by sudden resource saturation during peak user demand", "Prévention des pannes par saturation lors des pics de charge.")
        ],
        "practice": [
            ("Deliver an executive summary of quarterly infrastructure capacity runway:", ["Executive Summary: At current 12% MoM growth, our primary database storage maintains a 6-month capacity runway; we recommend expanding NVMe storage by Q3.", "Executive Summary: We have enough disk space for now.", "Executive Summary: Database is growing and we need more disk someday.", "Executive Summary: Storage is fine."], "Executive Summary: At current 12% MoM growth, our primary database storage maintains a 6-month capacity runway; we recommend expanding NVMe storage by Q3.", "Synthèse exécutive quantifiée avec délai d'autonomie et recommandation."),
            ("Document a resource exhaustion risk in an annual capacity forecast:", ["Capacity Risk: Without horizontal shard partitioning, the user-session cluster will exceed memory limits during the Black Friday traffic surge.", "Capacity Risk: Black Friday might be busy for servers.", "Capacity Risk: Sessions will take RAM.", "Capacity Risk: Servers will work hard on Black Friday."], "Capacity Risk: Without horizontal shard partitioning, the user-session cluster will exceed memory limits during the Black Friday traffic surge.", "Identification formelle du risque de saturation."),
            ("Specify safety buffer requirements for cloud auto-scaling headroom:", ["Capacity Standard: All production auto-scaling groups must maintain a minimum 30% compute headroom buffer above average peak utilization.", "Capacity Standard: Keep some extra servers running.", "Capacity Standard: 100% CPU is fine before scaling.", "Capacity Standard: No buffer needed."], "Capacity Standard: All production auto-scaling groups must maintain a minimum 30% compute headroom buffer above average peak utilization.", "Norme de marge de sécurité (headroom buffer)."),
            ("Propose proactive hardware provisioning based on linear trend analysis:", ["Based on telemetry trend extrapolation, we propose commissioning three additional Kubernetes worker nodes in October to absorb projected Q4 load increases.", "Let's buy 3 servers because Q4 is coming.", "We should add nodes when CPU hits 100%.", "We might need servers later."], "Based on telemetry trend extrapolation, we propose commissioning three additional Kubernetes worker nodes in October to absorb projected Q4 load increases.", "Proposition d'approvisionnement proactif motivée par la télémétrie.")
        ]
    }
})
print(f"CURRICULUM_149_160 loaded with {len(CURRICULUM_149_160)} lessons.")
